### ISSUE TITLE
mpv (w/ ytdl) fails, but ytdl works standalone

### ISSUE THREAD

**Issue by enilfodne** [netblue30/firejail#2833] opened 2019-07-06 21:14 UTC
Hi,

I seem to have a weird issue where im unable to use `mpv` ytdl, but `ytdl` works fine standalone.

Setup:

- `youtube-dl` - 2019.07.02 (installed via `pip` in the user directory `~/.local/bin/youtube-dl`)
- `mpv` - 0.29.1
- `firejail` - 0.9.60

Running:

```
firejail --profile=~/.config/firejail/custom.profile mpv --msg-level=ytdl_hook=debug -v "https://www.youtube.com/watch?v=tTGXBK69f0s"
```

Results in:

```
...
[ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=tTGXBK69f0s 
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
[cplayer] finished playback, unrecognized file format (reason 4)
[cplayer] Failed to recognize file format.
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
...
```

Running the command from the output above:

```
firejail --profile=~/.config/firejail/custom.profile youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=tTGXBK69f0s 
```

Seems to work as expected (`youtube-dl` returns a serialized JSON object).

The `custom.profile`, I'm currently testing with is the following:

```
whitelist ${HOME}/.local/bin/youtube-dl
whitelist ${HOME}/.local/lib/python3.7

include /etc/firejail/mpv.profile
include /etc/firejail/youtube-dl.profile

noblacklist ${PATH}/python3*
noblacklist /usr/lib/python3*
```

Any ideas how i might debug this further?

**Comment by glitsj16** [comment] 2019-07-07 04:00
@enilfodne I cannot reproduce, your first command works fine for me. What you're seeing might be due to youtube-dl parameters in your mpv config file(s). Both mpv and youtube-dl have a pile of options and I'm guessing you might have stale or breaking `ytdl-raw-options` hanging around. Does it work if you temporarily move any mpv configuration out of the way?

**Comment by enilfodne** [comment] 2019-07-07 09:17
Thanks for the suggestion, I've removed the configuration folder, but it doesn't seem to change anything (the log looks identical).

**Comment by rusty-snake** [comment] 2019-07-07 09:41
@enilfodne does mpv + ytdl work without firejail? (`sudo firecfg --clear`, `mpv --msg-level=ytdl_hook=debug -v "https://www.youtube.com/watch?v=tTGXBK69f0s"`)

**Comment by enilfodne** [comment] 2019-07-07 10:37
Yes, `mpv` works fine outside `firejail`.

Ok, so the culprit is that I've installed `youtube-dl` locally (`pip --user`). When installed system-wide (`sudo pip install`), everything works as expected.

Any ideas how i can change my profile to accommodate a local install?

**Comment by glitsj16** [comment] 2019-07-07 10:48
@enilfodne Nice catch. If you still want youtube-dl installed under your ${HOME}, I believe you'd need `ignore noexec ${HOME}` for 0.9.60. Both profiles have seen changes since that release, so you might look at these in git master to double-check if you're covering all bases in your custom profile. On a side-note, including both mpv.profile and youtube-dl.profile from /etc/firejail might cause unexpected conflicts. I would advise to make a single custom profile based on mpv.profile and add in what is needed to accommodate for a locally installed youtube-dl.

**Comment by rusty-snake** [comment] 2019-07-07 10:58
@enilfodne 
```
include /etc/firejail/mpv.profile
include /etc/firejail/youtube-dl.profile
```
Isn't a goog idea, because youtube-dl.profile contains  `machine-id` which break sound, ...
```
whitelist ${HOME}/.local/bin/youtube-dl
whitelist ${HOME}/.local/lib/python3.7
```
mpv.profile and youtube-dl.profile are both no `whitelist`ing profiles, that will break mpv-config and more.
```
noblacklist ${PATH}/python3*
noblacklist /usr/lib/python3*
```
`mpv.profile` already allow python.

Try as `custom.profile`:
```
quiet
include globals.local

ignore noexec ${HOME}

noblacklist ${HOME}/.config/mpv
noblacklist ${HOME}/.netrc

# Allow python (blacklisted by disable-interpreters.inc)
include allow-python2.inc
include allow-python3.inc

include disable-common.inc
include disable-devel.inc
include disable-exec.inc
include disable-interpreters.inc
include disable-passwdmgr.inc
include disable-programs.inc
include disable-xdg.inc

include whitelist-var-common.inc

apparmor
caps.drop all
netfilter
nodbus
nogroups
nonewprivs
noroot
nou2f
protocol unix,inet,inet6
seccomp
shell none
tracelog

disable-mnt
private-bin env,mpv,python*,youtube-dl
private-dev
private-tmp
```

**Comment by rusty-snake** [comment] 2019-07-07 11:01
@glitsj16 was faster, but my network to slow :grinning: .

**Comment by enilfodne** [comment] 2019-07-07 11:06
Thank you for the taking the time to write this.

It's working as expected, but only one minor issue remains. How can i get this integrated with a `firefox` profile? Reason being is that i want to utilize `ff2mpv`, which is a bridge between `firefox` and `mpv`.

**Comment by rusty-snake** [comment] 2019-07-07 11:07
Or as a script to force mpv to use ytdl with serveral URLs and strict firejail sandbox:
```zsh
#!/usr/bin/env zsh
while [[ -n "$@" ]]; do
        firejail --private --private-tmp --nodvd --notv --novideo --disable-mnt --ipc-namespace --private-etc="ld.so.cache,ld.so.preload,ld.so.conf,ld.so.conf.d,locale,locale.alias,locale.conf,localtime,alternatives,mime.types,xdg,ca-certificates,ssl,pki,crypto-policies,nsswitch.conf,resolv.conf,protocols,services,rpc,alsa,asound.conf,pulse,machine-id,fonts,pango,X11,drirc,glvnd,mpv,youtube-dl" --ignore="noexec ${HOME}" mpv "ytdl://$1"
        shift
done
```

**Comment by rusty-snake** [comment] 2019-07-07 11:15
Try `firefox.local`:
```
ignore noexec ${HOME}

whitelist ${HOME}/.local/bin/youtube-dl
whitelist ${HOME}/.local/lib/python3.7
```
First check if mpv+ytdl can run under the firefox profile.
`firejail --profile=firefox mpv "ytdl://SOMETHING"`

**Comment by enilfodne** [comment] 2019-07-07 11:53
Apologies for misleading you, but the `custom.profile` above and the `cli` example are not working. I can execute `youtube-dl`, but `mpv` can't find it. It appears that `ignore noexec ${HOME}` is not enough.

**Comment by rusty-snake** [comment] 2019-07-07 12:07
@enilfodne `firejail --noprofile mpv "ytdl://SOMETHING"`. I'm assuming that `${HOME}/.local/bin/` is in `$PATH`.

**Comment by enilfodne** [comment] 2019-07-07 12:27
Yes `~/.local/bin` is in `PATH` and the example above works (`noprofile`).

When trying to run it through (`mpv`) profile, it fails.

Its embarrassing, but i forgot to check the logs, clearly it states:

```
apparmor="DENIED" operation="exec" profile="firejail-default" name="/home/joffrey/.local/bin/youtube-dl" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000
```

Commenting out `apparmor` and `seccomp` in the `mpv` profile, works as expected.

Is there more info on both commands and how i can debug this further?

**Comment by rusty-snake** [comment] 2019-07-07 12:34
@enilfodne `apparmor` use the firejail-default AA profile. That you use AA make some error clear, but I'm wondering that you need to comment `seccomp`.
> Is there more info on both commands and how i can debug this further?

`seccomp`: uncomment it (leave `apparmor` commentet), `sudo journalctl | grep syscall`

**Comment by rusty-snake** [comment] 2019-07-07 12:35
You can first ignore `apparmor`, because if you want to firefox has a own AA profile AFAIK.

**Comment by enilfodne** [comment] 2019-07-07 12:51
Removing `apparmor` from the `firefox-common.profile` (same with the `mpv.profile`) and everything works as expected.

Would this reduce the security or negatively impact the isolation when `mpv` and `youtube-dl` are spawned within the same `firefox` sandbox?

**Comment by rusty-snake** [comment] 2019-07-07 13:46
> Would this reduce the security

Yes, you should consider tweaking the FF-AA-Profile instead, but there I can't help you.

**Comment by enilfodne** [comment] 2019-07-07 14:27
After looking at `firejail-default`, there's a comment stating:

```
##########
# Allow running programs only from well-known system directories. If you need
# to run programs from your home directory, uncomment /home line.
##########
```

thus uncommenting:

```apparmor
#/{,run/firejail/mnt/oroot/}home/** ix,
```

Fixed all those problems and allowed me to re-enable `apparmor` on all profiles.

Thanks against for taking some time to help me debug this.

**Comment by rusty-snake** [comment] 2019-07-07 15:18
@enilfodne closing here, please fell free to reopen if you have more questions.

**Closed by rusty-snake** 2019-07-07 15:18 UTC
Labels: information
