### ISSUE TITLE
Firefox does not work with Firejail on Mint 20

### ISSUE THREAD

**Issue by rpellew** [netblue30/firejail#3507] opened 2020-07-10 09:12 UTC
Hi
I just upgraded my system to Linux Mint 20. 
Firefox no longer works with Firejail. 
It appears to start, but nothing at all appears on the screen, and I have to manually kill the process.

firejail 0.9.62
firejail-profiles 0.9.62
firefox 78.0.1

If I comment out the seccomp lines in firefox-common.profile, it allows it to start. So I assume it is making some calls that need to be allowed. I don't know to find out. I have tried the --trace and --tracelog options but nothing appears in the syslog. 

Thanks.

**Comment by rusty-snake** [comment] 2020-07-10 11:36
AMD GPU?  Add `!kcmp`.

> I have tried the --trace and --tracelog options but nothing appears in the syslog.

They are for files (e.g. blacklist) and don't affect seccomp. For seccomp you need audit, see `man 8 auditctl`

**Comment by rpellew** [comment] 2020-07-10 14:58
Hi rusty-snake
Yeah, AMD GPU. That fixed it. 
Appreciate your help.

**Comment by rusty-snake** [comment] 2020-07-10 15:09
This is caused by Mesa (see #3219 for more details) and fixed in the next release (#3301).

**Closed by rusty-snake** 2020-07-10 15:09 UTC
