### ISSUE TITLE
npm and pip profiles

### ISSUE THREAD

**Issue by muziker** [netblue30/firejail#4166] opened 2021-04-05 05:36 UTC
These are two very popular methods of installing new libraries for coding. Is there a profile for keeping these sandboxed? npm by default installs node_modules locally in the project, and python's pip can have separate library paths from the system installed python using virtualenv.  Since both these library managers, together with their interpreters themselves can be compiled and installed separate from the system versions, a sandbox that restricts these should work. Has anyone got a profile for this? Or is the default profile good enough?

**Comment by rusty-snake** [comment] 2021-04-05 07:26
npm has a profile ([npm.profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/npm.profile)) which you can easily find by searching for `npm.profile` on https://github.com/netblue30/firejail/find/master and pip has no profile yet.

**Comment by rusty-snake** [comment] 2021-04-05 07:27
Duplicate of #2666

**Comment by muziker** [comment] 2021-04-05 08:00
I was using the repo version of firejail, so the newer profile isn't there.

**Comment by rusty-snake** [comment] 2021-06-10 08:53
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.

**Closed by rusty-snake** 2021-06-10 08:53 UTC
