### ISSUE TITLE
How to open links in firejailed Firefox with firejailed JDownloader?

### ISSUE THREAD

**Issue by ihasaquesion** [netblue30/firejail#3579] opened 2020-08-09 19:11 UTC
When running JDownloader with firejail like so: `firejail --profile=/etc/firejail/JDownloader.profile bash /path/JDownloader2/JDownloader2` I can't get it to open a webpage with a captcha in firejailed Firefox-ESR. It either launches it but it doesn't open a page and just closes again or nothing happens.

I used to get the error "Your Firefox profile cannot be loaded. It may be missing or inaccessible" and I might get it again when using an improved JDownloader.profile that allows Firefox-ESR. In that case I'd like to know how solve this problem without having to delete any Firefox profiles.

I used to use a workaround where I output the link to the captcha so that I can manually copy the link and open it in the firejailed Firefox-ESR by changing the _Browser Commandline_ of the BrowserCaptchaSolver in the Advanced Settings of JDownloader2.

I'd like to get it to open the Webpage when clicking "Open Browser". Opening dlc/cnl files/links in JDownloader2 via firejailed Firefox work (while others do not but this could be a firewall issue).

This might also be a problem with JDownloader2 or Firefox-ESR.

**Environment**
firejail version 0.9.62

**Comment by rusty-snake** [comment] 2020-08-09 19:14
Duplicate of #2336

**Comment by rusty-snake** [comment] 2020-08-09 19:42
see also https://github.com/netblue30/firejail/issues/3471#issuecomment-646582480

**Comment by ihasaquesion** [comment] 2020-08-09 19:45
Thanks. The solution of #2336 was to add `include chromium.profile` to the profile.
The Browser Commandline setting udner Advanced settings needs to be [ "firejail", "firefox-esr", "%s" ]

**Comment by rusty-snake** [comment] 2020-08-12 16:59
> Please also let me know how to allow it to run a specific executable under /usr/bin/ for a workaround until opening webpages with firefox works.

/usr/bin is not restricted in JDownloader.profile

**Comment by ihasaquesion** [comment] 2020-08-13 15:32
> /usr/bin is not restricted in JDownloader.profile

I can make JDownloader run a file in /usr/bin by changing [ "firejail", "firefox-esr", "%s" ] in the JDownloader settings when using the default firejail profile (running JDownloader with `firejail --profile=/etc/firejail/JDownloader.profile bash /path/JDownloader2/JDownloader2`).
I can't do so when using the JDownloader.profile even when the file is set to noblacklist (I get an error when trying to whitelist it). It also doesn't work when moving the file into /path/JDownloader2/.
And that would only be the workaround.

**Comment by rusty-snake** [comment] 2020-11-09 19:45
still need help?

**Comment by ihasaquesion** [comment] 2020-12-03 16:18
Well, it didn't work with the captchas but now JDownloader2 doesn't start up at all (getting the error below):

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:132)
	at org.jdownloader.update.launcher.JDLauncher.main(JDLauncher.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdownloader.updatev2.JDClassLoaderLauncher.main(JDClassLoaderLauncher.java:128)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.appwork.utils.os.CrossSystem
	at org.appwork.utils.logging.LogFormatter.<init>(LogFormatter.java:57)
	at org.appwork.utils.logging2.LogConsoleHandler$1.<init>(LogConsoleHandler.java:54)
	at org.appwork.utils.logging2.LogConsoleHandler.<init>(LogConsoleHandler.java:54)
	at org.appwork.utils.logging2.LogSourceProvider.<init>(LogSourceProvider.java:137)
	at org.appwork.utils.logging2.extmanager.LoggerFactory.<init>(LoggerFactory.java:148)
	at org.appwork.utils.logging2.extmanager.LoggerFactory.initialize(LoggerFactory.java:128)
	at org.appwork.utils.logging2.extmanager.LoggerFactory.<clinit>(LoggerFactory.java:57)
	at org.appwork.utils.logging2.LogSourceRedirector.getDefaultLogger(LogSourceRedirector.java:64)
	at org.appwork.loggingv3.LogV3.info(LogV3.java:101)
	at org.appwork.utils.Application.setApplication(Application.java:881)
	at org.jdownloader.update.launcher.SecondLevelLauncher.<clinit>(SecondLevelLauncher.java:85)
	at org.jdownloader.update.launcher.JDLauncherViaClassLoader.main(JDLauncherViaClassLoader.java:10)
	... 12 more
```

I could not find out why it's having this error and one forum post recommended reinstalling.

Maybe this issue could be solved with comments in that Thunderbird issue. However, it looks like JDownloader2 isn't entirely open source so [I'm switching to pyLoad](https://github.com/pyload/pyload/issues/3850) (I think as long as JD2 isn't verifiably fully open source and switching to pyLoad is possible this issue could be closed).

**Closed** 2021-01-04 12:16 UTC
Labels: duplicate, question
