### ISSUE TITLE
libpostexecseccomp.so in /run/firejail/lib/libpostexecseccomp.so apparmor issue

### ISSUE THREAD

**Issue by adrelanos** [netblue30/firejail#2947] opened 2019-09-07 06:04 UTC
Tor Browser 8.5.5 with firejail and https://github.com/Whonix/apparmor-profile-torbrowser

> Sep 07 03:25:54 host kernel: audit: type=1400 audit(1567826754.074:42): apparmor="DENIED" operation="open" profile="/**/*-browser/Browser/firefox" name="/run/firejail/lib/libpostexecseccomp.so" pid=7879 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

Does libpostexecseccomp.so really have to reside in `/run/firejail/lib/libpostexecseccomp.so`?

Ideally firejail would not cause apparmor issues.

Maybe the (upcoming deepening on your apparmor version) `abstractions/base.d` would help?

`abstractions/base.d` as per https://gitlab.com/apparmor/apparmor/issues/50

**Comment by Vincent43** [comment] 2019-09-07 15:12
> Ideally firejail would not cause apparmor issues.

I would say that firejail regularly causes issues for apps confined with standalone AppArmor profiles and the other way around. In effect you would need to weaken both firejail and apparmor profiles which makes the sense of running them both questionable.

**Comment by smitsohu** [comment] 2019-09-18 19:38
Thanks for pointing to this `abstractions/base.d` thing!

Though probably (and unfortunately) it will take a while to arrive in the mainstream distributions.

**Comment by adrelanos** [comment] 2019-09-22 05:55
@Vincent43

> I would say that firejail regularly causes issues for apps confined with standalone AppArmor profiles and the other way around. In essence they are blocking each other from functioning. In effect you would need to weaken both firejail and apparmor profiles which makes the sense of running them both questionable.

Would be good to have either a technical explanation, examples and/or authoritative statement on that.

**Comment by Vincent43** [comment] 2019-09-22 10:34
AppArmor sandbox is path based and uses whitelist approach by default. Firejail sandbox is also path based and uses blacklist approach by default. It also uses namesapces and rewrites some paths in sandbox which cause denials in AppArmor as you can see. The only case supported by firejail related to AppArmor is using `firejail-default` generic profile which shouldn't cause issues. Users who want to use app specific profiles with firejail are on their own as there is nothing firejail can do to help them. I can't and won't authoritatively force you on anything  but avoiding using app specific AppArmor profile with firejail is my best advice.

**Comment by Vincent43** [comment] 2019-09-22 16:15
I try to reply all questions from first post:

> Does libpostexecseccomp.so really have to reside in /run/firejail/lib/libpostexecseccomp.so?

Yes, it's bind-mounted there from `/usr/lib/firejail` and needed there for firejail to work.

> Ideally firejail would not cause apparmor issues.

This issue is caused by your custom apparmor profile not allowing firejail creating its own sandbox. There are unlimited ways for apparmor to block firejail from functioning and firejail can really prevent this happening on your own.

> Maybe the (upcoming deepening on your apparmor version) abstractions/base.d would help?

In this case firejail's apparmor integration isn't used at all so all apparmor tweaks belong to your custom profile.

I hope this help understanding the problem better.

**Comment by Vincent43** [comment] 2019-10-09 20:30
Closing as questions were answered. Feel free to ask new ones if something is still unclear.

**Closed by Vincent43** 2019-10-09 20:30 UTC
Labels: question
