### ISSUE TITLE
Gimp not working

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#2658] opened 2019-04-21 05:10 UTC
Specs- Manjaro(KDE): kernel-4.19.34.1, Firejail-0.9.58.2-1, GIMP-2.10.10-1

I tried to open gimp but nothing launches. When I looked at task manager it shows gimp as [zombie](https://imgur.com/Ov7x5fn). Don't know what goes wrong. [Debug](https://gist.github.com/Neo00001/c30e3939b547c5646bb42904c5831f97)

**Comment by FOSSONLY** [comment] 2019-04-21 06:18
Hm.. with Debian-Buster and Firejail 0.9.58, Gimp is running flawlessly. I would kill all Gimp/Firejail instances, and retest it again. Sometimes a process hangs under some circumstances, what block new instance of same process. I didn't found any other problems.

**Comment by Neo00001** [comment] 2019-04-21 06:44
> Hm.. with Debian-Buster and Firejail 0.9.58, Gimp is running flawlessly. I would kill all Gimp/Firejail instances, and retest it again. Sometimes a process hangs under some circumstances, what block new instance of same process. I didn't found any other problems.

same thing is happening with kdenlive. Most likely, it's an arch issue. Although browsers & many other apps are working flawlessly.

**Comment by curiosity-seeker** [comment] 2019-04-21 10:59
Have you tried `firejail --debug /usr/bin/gimp` ? What's the output of `echo $PATH` ? I'm asking because I'm also using Manjaro and I had to modify the PATH as `/usr/local/bin` was not included (or, at least, not at the beginning of PATH). I added the following to ~/.bashrc:

`export PATH="/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/seeker/bin"

If my assumption is correct, `firejail --list` should reveal that your browser etc. are **not** sandboxed.

**Comment by Neo00001** [comment] 2019-04-21 14:53
> If my assumption is correct, `firejail --list` should reveal that your browser etc. are **not** sandboxed.

Apart from gimp & kdenlive, everything else is working for me. Both are being showed as zombie. 
debug output- https://gist.github.com/Neo00001/c30e3939b547c5646bb42904c5831f97

**Comment by Neo00001** [comment] 2019-04-21 18:47
btw, firejail --noprofile is working for gimp.

**Comment by glitsj16** [comment] 2019-04-28 07:08
@Neo00001 Looking at your debug log, I see this on line 482:

`Warning: an existing sandbox was detected. /usr/bin/gimp will run without any additional sandboxing features`

To me that suggests gimp was called from within another firejailed application (an image-viewer or the likes?). If so, that would explain what you're describing. As a general rule, applications started from within any other firejailed program inherit the parent's profile. And in this case that profile isn't built to access gimp. If what I'm describing here fits your use-case, try starting gimp independently and open whatever image file(s) you need from within gimp.

**Comment by rusty-snake** [comment] 2019-05-11 13:55
@Neo00001 duplicate of #2681?

**Comment by Neo00001** [comment] 2019-05-12 00:55
@rusty-snake I've re-installed manjaro & after that everything is working smoothly again.I'm not sure what actually did go wrong.

**Comment by chiraag-nataraj** [comment] 2019-05-22 11:02
Great! Glad to hear it resolved itself on your end :)

**Closed by chiraag-nataraj** 2019-05-22 11:02 UTC
