### ISSUE TITLE
LibreWolf isn't automatically firejailed with sudo firecfg on Linux Mint 21

### ISSUE THREAD

**Issue by Dyras** [netblue30/firejail#5460] opened 2022-11-07 08:30 UTC
### Description

_Describe the bug_
For some reason, running sudo firecfg on Linux Mint doesn't make LibreWolf run Firejailed. I believe this has to do with the path used for the default LibreWolf shortcut.

There's a thread on Reddit about this
https://www.reddit.com/r/LibreWolf/comments/yjgcpu/librewolf_isnt_automatically_firejailed_after/

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Install the repo version of LibreWolf
2. Install Firejail
3. Run sudo firecfg
4. Run LibreWolf
5. Run Firefox
6. Open the terminal and run firejail --list
7. Notice that only Firefox is running in Firejail

### Expected behavior
LibreWolf's default shortcuts in the system should launch LibreWolf in Firejail, as anticipated

### Actual behavior
LibreWolf's default shortcuts on Linux Mint aren't launching LibreWolf in Firejail.

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a terminal?_
Didn't try it, but this is seemingly related to shortcuts

### Additional context

Quoted from Reddit:
I think I've figured it out. The default shortcut for LibreWolf is:

`/usr/share/librewolf/librewolf %u`

The default shortcut for Firefox is:

`firefox %u`

If I change the shortcut for LibreWolf to the below, it works:

`librewolf %u`

Basically, it seems like Firejail doesn't take the changed shortcut into account.

Additionally, running `firejail /usr/share/librewolf/librewolf %u` breaks the program, while running `firejail librewolf` works flawlessly

### Environment

Linux Mint 21
firejail version 0.9.70

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

The long debug log:
https://pastebin.com/EFNvk8ha

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
pcadmin@pc:~$ firejail /usr/share/librewolf/librewolf
Reading profile /home/pcadmin/.config/firejail/librewolf.profile
Reading profile /etc/firejail/librewolf.profile
Reading profile /etc/firejail/whitelist-usr-share-common.inc
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-proc.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 6118, child pid 6121
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Warning: cleaning all supplementary groups
Child process initialized in 201.65 ms
defaults/preferences/firefox.js:6: prefs parse error: expected ',' after pref name
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: VA-API test failed: no supported VAAPI profile found. (t=1.38854) [GFX1-]: glxtest: VA-API test failed: no supported VAAPI profile found.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory.

Parent is shutting down, bye...

**Comment by Dyras** [comment] 2022-11-22 13:38
I just tested on Debian and the exact same thing is happening. Firefox runs in Firejail automagically, LibreWolf just doesn't.

**Comment by marek22k** [comment] 2023-03-20 12:49
Is there a current workaround to firecfg librewolf?

**Comment by kmk3** [comment] 2023-04-05 16:49
Can this still be reproduced in firejail 0.9.72?

What is the output of the following commands on your system?

```console
$ grep '^Exec' /usr/share/applications/firefox.desktop
Exec=/usr/lib/firefox/firefox %u
Exec=/usr/lib/firefox/firefox --new-window %u
Exec=/usr/lib/firefox/firefox --private-window %u

$ grep '^Exec' /usr/share/applications/librewolf.desktop
Exec=/usr/lib/librewolf/librewolf %u
Exec=/usr/lib/librewolf/librewolf --new-window %u
Exec=/usr/lib/librewolf/librewolf --private-window %u
Exec=/usr/lib/librewolf/librewolf --ProfileManager %u

$ cat /usr/bin/firefox
#!/bin/sh
exec /usr/lib/firefox/firefox "$@"

$ cat /usr/bin/librewolf
#!/bin/sh
exec /usr/lib/librewolf/librewolf "$@"
```

What are the versions of firefox/librewolf used?  Where are they installed
from (normal distro repository/AppImage/etc)?

On Artix:

```console
$ pacman -Q firefox librewolf
firefox 111.0.1-1
librewolf-bin 111.0.1-1
```

One guess: firecfg checks whether the program in the `Exec=` line is in the
path, so maybe /usr/bin/firefox exists but not /usr/bin/librewolf.

Does creating the following file and re-running `firecfg` succeed as a
workaround?

~/bin/librewolf:

```
#!/bin/sh
exec firejail /usr/bin/librewolf
```

Run:

```sh
PATH="$HOME/bin:$PATH"
export PATH
sudo firecfg
```

**Comment by rusty-snake** [comment] 2023-04-07 11:01
Duplicate of #2624

**Comment by rusty-snake** [comment] 2023-04-07 11:04
Same cause as in #2624 (this is issue number 5460 so we're 2836 issues later). The desktop file is not named after the profile file (or the other way around).

And same workaround as in #2624, create a `start-librewolf.profile`.

**Comment by marek22k** [comment] 2023-04-11 18:00
So I could use `ln -s /etc/firejail/librewolf.profile /etc/firejail/start-librewolf.profile`?

**Comment by rusty-snake** [comment] 2023-04-11 18:05
> Wouldn't it make sense to rename the profile in general or does the problem only occur with the Debian installation?

Then you would have a working firecfg but a broken firejail unless you rename the actual binary too.

**Comment by kmk3** [comment] 2023-04-11 20:56
(Offtopic)

@Dyras

Please see the following links for how to format code blocks in markdown:

* <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks>
* <https://github.github.com/gfm/#fenced-code-blocks>

**Comment by kmk3** [comment] 2023-04-11 20:57
@Dyras [on Apr 7](https://github.com/netblue30/firejail/issues/5460#issuecomment-1500170621):

> The output of the following:
> 
> ```
> $ grep '^Exec' /usr/share/applications/librewolf.desktop
> ```
> 
> Is that the file can't be found.
> 
> However, the output of the following is as follows:
> 
> ```
> $ grep '^Exec' /usr/share/applications/start-librewolf.desktop
> Exec=/usr/share/librewolf/librewolf %u
> Exec=/usr/share/librewolf/librewolf
> Exec=/usr/share/librewolf/librewolf --private-window %u
> Exec=/usr/share/librewolf/librewolf --safe-mode
> Exec=/usr/share/librewolf/librewolf --preferences
> ```

Created a MR upstream to attempt to fix this:

* [Rename start-librewolf.desktop to librewolf.desktop](https://gitlab.com/librewolf-community/browser/bsys5/-/merge_requests/17)

**Comment by kmk3** [comment] 2023-04-15 01:56
> Created a MR upstream to attempt to fix this:
> 
> * [Rename start-librewolf.desktop to librewolf.desktop](https://gitlab.com/librewolf-community/browser/bsys5/-/merge_requests/17)

Good news: It was merged!

Let us know if anything changes when the next LibreWolf version is released.

Closing this for now.

**Closed by kmk3** 2023-04-15 01:56 UTC
Labels: firecfg, notourbug
