### ISSUE TITLE
fcopy: Failure to copy file when uid != root

### ISSUE THREAD

**Issue by miszr** [netblue30/firejail#1531] opened 2017-09-05 13:23 UTC
Isssue #1243 still exists.

My system is configured with systemd-networkd and systemd-resolved.

The file /etc/resolv.conf is symlinked to /run/systemd/resolve/resolv.conf with the following permissions:
-rw-r--r-- systemd-resolve systemd-resolve /run/systemd/resolve/resolv.conf

So the file is _world readable_, but fcopy still refuses to copy it.

The issue is that fcopy only checks the uid of the file, not respecting the actual permissions set on it.

An example where this would fail terribly is if a file owner had no permissions.

To reproduce:
1. Create a file with a certain owner that is not root.
2. Run fcopy as root and try to copy that file.

**Comment by ranisalt** [comment] 2017-09-13 01:36
I can reproduce too, I have the same setup with systemd-resolved.

**Comment by netblue30** [comment] 2017-09-14 12:57
I put a fix in for issue: https://github.com/netblue30/firejail/issues/1547

I think is the same problem, /run/systemd/resolve/resolv.conf was blacklisted in /etc/firejail/disable-common.inc. Give it a try, thanks.

**Comment by miszr** [comment] 2017-09-14 13:01
No, #1547 is a different issue.

I corrected mine a while back using `noblacklist /var/run/systemd` in `/etc/firejail/globals.local`

**Comment by netblue30** [comment] 2017-09-15 11:10
Sorry, actualy I removed /var/run/systemd from disable-common.inc, not /run/systemd/resolve/resolv.conf. The fix is in git.

**Comment by miszr** [comment] 2017-09-15 11:53
This issue is **NOT** resolved.

The problem is using fcopy to copy a world readable file but where the owner is not the current user.
Since firejail is using SUID to get root, the current user is root.

None of the above mentioned fixes are affecting the problem.

**Comment by eomanis** [comment] 2017-09-15 20:10
This problem is currently preventing me from launching Steam, which I have set up to be launched in a --private= home dir.

```
[myuser@mysystem ~]$ ls -la /etc/resolv.conf
lrwxrwxrwx 1 root root 32 15. Sep 21:51 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
[myuser@mysystem ~]$ ls -la /run/systemd/resolve/resolv.conf 
-rw-r--r-- 1 systemd-resolve systemd-resolve 536 15. Sep 14:36 /run/systemd/resolve/resolv.conf
```
Launching Steam:
```
[myuser@mysystem Steam]$ /usr/bin/firejail --profile=/etc/firejail/steam.profile --private="/home/myuser/sandboxes/Steam" -- /usr/bin/steam-runtime
Reading profile /etc/firejail/steam.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-common.local
Reading profile /home/myuser/.config/firejail/disable-common.local
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 26240, child pid 26241
Error fcopy: invalid file /etc/resolv.conf
Error: failed to run /usr/lib/firejail/fcopy
Error: proc 26240 cannot sync with peer: unexpected EOF
Peer 26241 unexpectedly exited with status 1
```
When I copy /run/systemd/resolve/resolv.conf to /etc/resolv.conf it works again, so apparently fcopy takes offense to /etc/resolv.conf being a symlink.
The weird thing is, why does this surface now? I have moved from NetworkManager to systemd-networkd and systemd-resolved recently because of some NetworkManager regression, but with NetworkManager I also had /etc/resolv.conf symlinked to the respective NetworkManager-generated file, and Steam worked back then.

**Comment by miszr** [comment] 2017-09-15 20:32
As mentioned in my original comment, the issue is clear. The reason that it does not work is **not** because of symlink, I have tested all of this.

**Comment by ranisalt** [comment] 2017-09-15 22:38
This is giving me more issues with other apps that can't copy the resolv.conf link. The apps fail to resolve any DNS address.

**Comment by netblue30** [comment] 2017-09-18 12:46
I have a fix in, give it a try. I'll reopen it if necessary, thanks.

**Closed by netblue30** 2017-09-18 12:46 UTC
Labels: bug

**Comment by miszr** [comment] 2017-09-19 07:03
The solution does work. However I do think the solution is overly specific.

The fundamental solution should be allowing world-readable files to be copied. Not allowing a specific file to be copied.

That the issue occurred with systemd-resolved is just one case.

**Comment by ranisalt** [comment] 2017-09-19 18:14
It didn't work for me, apps firejailed still can't resolve DNS. I recreated the links with `firecfg`.

**Comment by primeroz** [comment] 2021-08-22 16:54
I am still having this issue with resolv.conf -> /run/systemd/.... 

is this supposed to be fixed ?

**Comment by solsticedhiver** [comment] 2023-04-25 01:27
while using firejail and transmission for a while, this bug has just poop-up on my rpi3 system, for no reason ?
