### ISSUE TITLE
Cannot launch Evince from command line

### ISSUE THREAD

**Issue by birthstalker** [netblue30/firejail#1804] opened 2018-03-10 00:52 UTC
OS: ArchLinux x86_64
Firejail version: 0.9.52
(All packages are up to date)

Evince starts normally from Nautilus and other sandboxed softwares, but it is unable to launch evince from un-sandboxed one (e.g. terminal). It just stuck without any error message.

I just try to launch un-sandboxed nautilus and evince cannot start the same way with terminal.

```
Reading profile /etc/firejail/evince.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 3341, child pid 3342
Private /etc installed in 3.02 ms
Standard C library installed in 32.68 ms
Program libraries installed in 297.44 ms
GdkPixbuf installed in 13.26 ms
GTK3 installed in 28.03 ms
Pango installed in 0.01 ms
GIO installed in 6.19 ms
Installed 165 libraries and 5 directories
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 467.42 ms
```

Please take a look. If any more information or logs that could help you find the problem faster, please let me know.
Thank you very much.

**Comment by SkewedZeppelin** [comment] 2018-03-10 01:06
I'm experiencing this as well with quite a few profiles. I think it might be Arch related, and not firejail, as I cannot reproduce it on my Fedora machines.

**Comment by birthstalker** [comment] 2018-03-10 15:36
Maybe something has been changed in new version of softwares and libraries recently. Today I encounter the same problem with GNOME Calculator.

Do you know the way to gather more information, some kind of log or something that can make it easier for the developer to find the problem?

**Comment by SkewedZeppelin** [comment] 2018-03-10 15:46
@birthstalker Are you on a git build?

I just checked again, and I cannot launch many profiles on either Arch or Fedora, running from git on both.
eog, file-roller, gedit, gnome-calculator all seem to refuse to ever launch. Nothing ever appearing in logs.

**Comment by Fred-Barclay** [comment] 2018-03-10 17:42
I suspect we have two different bugs here. :)
I think #1803 is the cause of @birthstalker 's troubles and was fixed by @Vincent43 

@SkewedZeppelin All of the profiles you listed have `private-dev`, which has recently broken for me on Fedora with https://github.com/netblue30/firejail/commit/dda8b2dbaf85383c787b2e70982346779471a269 (see comments at bottom).

**Comment by SkewedZeppelin** [comment] 2018-03-10 18:36
That GitHub reply via email thing never works for me.

Anyway, I think you're correct. Lets close this.

**Closed by SkewedZeppelin** 2018-03-10 18:36 UTC
Labels: bug
