### ISSUE TITLE
regression in .9.64.2: private-tmp whitelists .X11-unix, but makes it read-only

### ISSUE THREAD

**Issue by jonleivent** [netblue30/firejail#4381] opened 2021-07-02 17:07 UTC
I am testing upgrading firejail from .9.58.2 to .9.64.2, and found that the private-tmp behavior with respect to whitelisting the .X11-unix dir has changed.  In .9.58.2, the whitelisting of .X11-unix left it writable, allowing the firejailed process (Xephyr, for instance) to create new sockets.  In .9.64.2, .X11-unix is read-only, and cannot be made writable with the read-write option either.  As a result, Xephyr subprocesses that use private-tmp don't work.

Is there some additional setting somewhere in .9.64.2 that will leave .X11-unix writable when using private-tmp, or do I have to abandon using private-tmp?

**Comment by rusty-snake** [comment] 2021-07-02 17:11
Duplicate of #4244

**Closed** 2021-07-02 17:12 UTC
