### ISSUE TITLE
Add a profile for x2goserver

### ISSUE THREAD

**Issue by mabra** [netblue30/firejail#5837] opened 2023-05-24 15:38 UTC
### Is your feature request related to a problem? Please describe.

In my setup (to protect me from attempts of browsers to access any identifyable properties), I am using Firefox in a KVM machine and use this over x2go.
Found not way, to make sound possible, everything else looks working.

### Describe the solution you'd like

I am not that deep in Linux, but seeing(!!), that an unprotected Fox communicates over the LO interface, while the jailed version cannot. From my understanding, the x2goserver uses the LO interface to redirect (the window and even) the sound, where the x2goagant bridges the traffic (from LO to the right interface). Using a terminal over x2go can "paplay" a sound.

Need a profile for the x2goserver!?
The network in this situation is already well protected by iptables and there is NO way out, except for a lan-based squid proxy (no auto, interface per browser-profile). In my situation, protecting Firefox to use the network is not necessary at all!?
Found no way to run Firefox with the normal network (probably too deept in the docs?), keeping all other protections by firejail in place.

### Describe alternatives you've considered
Searching internet, considering netcat - too complicated for me at the moment.

**Comment by kmk3** [comment] 2024-09-10 11:49
Duplicate of #1139

**Closed by kmk3** 2024-09-10 11:49 UTC
Labels: profile-request
