### ISSUE TITLE
No Audio in Zoom

### ISSUE THREAD

**Issue by epsilontheta** [netblue30/firejail#3369] opened 2020-04-20 08:48 UTC
When starting zoom in firejail I cannot use the "connect audio" and therefore can't use audio in&output.

Also I saw this in the firejail output:

```
No PulseAudio daemon running, or not running as session daemon.
zoom started.
```

Even though that's not the case and I executed the command as the same user as the pulseaudio daemon.

**Comment by rusty-snake** [comment] 2020-04-20 08:56
Duplicate of #3336

**Comment by rusty-snake** [comment] 2020-04-20 08:57
my guess (unverified): https://github.com/netblue30/firejail/issues/3336#issuecomment-613292223

**Closed** 2020-04-20 08:58 UTC

**Comment by bouncinglime** [comment] 2020-04-24 21:37
I don't think this is a duplicate; as the reporter of #3336 I do get audio in Zoom. (Occasionally my mic doesn't work but that's a different issue. Usually it does when I plug my headphones w/ mic in before launching the app.)

**Comment by rusty-snake** [comment] 2020-04-24 21:47
They are somewhat different symptoms, but the same error message. Therefore I assumed it has the same reason.
