### ISSUE TITLE
telegram.profile need netlink protocol

### ISSUE THREAD

**Issue by IlyaIndigo** [netblue30/firejail#3733] opened 2020-11-08 04:11 UTC
When running telegram via firejail, it issues a warning.
Could not create AF_NETLINK socket (Operation not supported)
Please change telegram.profile to enable netlink protocol.

-protocol unix,inet,inet6
+protocol unix,inet,inet6,netlink

**Comment by glitsj16** [comment] 2020-11-08 04:27
Duplicate of #3614.

You can make the needed change in a telegram.local file until your OS packages the firejail version that has that option.

**Closed by glitsj16** 2020-11-08 04:27 UTC

**Comment by IlyaIndigo** [comment] 2020-11-08 04:35
Thank you!
