### ISSUE TITLE
Can't start qpdfview

### ISSUE THREAD

**Issue by omega3** [netblue30/firejail#2852] opened 2019-07-10 09:26 UTC
```
firejail --net=none qpdfview
Reading profile /etc/firejail/qpdfview.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 4647, child pid 4648
1 program installed in 4.06 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 101.54 ms
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
Qt: Session management error: Could not open network socket

```

and it hangs here.

The same with:

```
firejail qpdfview
Reading profile /etc/firejail/qpdfview.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 4849, child pid 4850
1 program installed in 4.54 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized in 90.82 ms
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
```

Only just
```
$ qpdfview
qt.core.logging: Ignoring malformed logging rule: '’*=false’'
```

start normally. 
It happened after recent updates in Manjaro. So far it was working fine.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.2
KDE Frameworks Version: 5.59.0
Qt Version: 5.13.0
Kernel Version: 5.1.16-1-MANJARO
OS Type: 64-bit

firejail - version 0.9.60

**Comment by rusty-snake** [comment] 2019-07-10 09:41
Maybe a duplicate of #2834.

@omega3 does this fix it for you: https://github.com/netblue30/firejail/commit/3d73fa92b83778fb373d24cd546b3d5b0e376529?

**Comment by omega3** [comment] 2019-07-10 13:03
Yes. Thank you.

**Closed** 2019-07-10 13:12 UTC
Labels: duplicate
