### ISSUE TITLE
Gnome-calculator not working in firejail 0.9.46

### ISSUE THREAD

**Issue by qazip** [netblue30/firejail#1300] opened 2017-05-22 18:02 UTC
This is the output after trying to run gnome-calculator:

```
gnome-calculator 
Reading profile /etc/firejail/gnome-calculator.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 9613, child pid 9614
Child process initialized in 46.05 ms

(gnome-calculator:7): Gdk-ERROR **: The program 'gnome-calculator' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 178 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Parent is shutting down, bye...
```

I'm using Ubuntu 16.04 and I did "sudo firecfg".

**Comment by Fred-Barclay** [comment] 2017-05-22 18:18
I can't reproduce on my system (Debian Sid with the MATE desktop), either with or without firecfg. 

What happens if you remove the links created by firecfg with `sudo firecfg --clean` and then run `firejail gnome-calculator`? What about if you just run `gnome-calculator`?

**Comment by qazip** [comment] 2017-05-22 18:35
After removing the links, `gnome-calculator` runs fine, `firejail gnome-calculator` does not:

```
firejail gnome-calculator
Reading profile /etc/firejail/gnome-calculator.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 12407, child pid 12408
Child process initialized in 71.47 ms

(gnome-calculator:7): Gdk-ERROR **: The program 'gnome-calculator' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 178 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

Parent is shutting down, bye...

```

**Comment by SYN-cook** [comment] 2017-05-22 22:40
Can you please try `firejail --ignore=ipc-namespace gnome-calculator` and let us know if that works?

**Comment by qazip** [comment] 2017-05-23 06:30
Yes, that worked:

```
firejail --ignore=ipc-namespace gnome-calculator
Reading profile /etc/firejail/gnome-calculator.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 4606, child pid 4607
Child process initialized in 84.37 ms

** (gnome-calculator:7): WARNING **: currency.vala:407: Currency LTL is not provided by IMF or ECB

```

**Comment by SYN-cook** [comment] 2017-05-23 11:08
@qazip Nice! Thanks for the bug.

**Comment by netblue30** [comment] 2017-05-23 13:06
all merged.

**Closed** 2017-05-23 13:06 UTC
