### ISSUE TITLE
/usr/local/bin/dirname apparmor issue

### ISSUE THREAD

**Issue by adrelanos** [netblue30/firejail#2948] opened 2019-09-07 06:08 UTC
Tor Browser 8.5.5 with firejail and https://github.com/Whonix/apparmor-profile-torbrowser

> Sep 07 03:42:10 host kernel: audit: type=1400 audit(1567827730.866:126): apparmor="DENIED" operation="exec" profile="/**/*-browser/Browser/firefox" name="/usr/local/bin/dirname" pid=15407 comm="firefox" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0

Does not happen without firejail.

There is no such file /usr/local/bin/dirname. There are no files in /usr/local/bin.

Why does firejail try to execute something form that folder? Avoidable? Could you fix that apparmor issue in a generic way somehow?

Perhaps similar solution as for https://github.com/netblue30/firejail/issues/2947?

**Comment by Vincent43** [comment] 2019-09-07 15:03
I don't know the reason of this specific issue but you may reconsider if it does make sense running app with both firejail and custom tailored AppArmor profile. It will get you troubles like that and security benefits will be mostly redundant.

**Comment by adrelanos** [comment] 2019-09-21 10:19
Do you agree with this sentiment? @netblue30

**Comment by Vincent43** [comment] 2019-09-21 19:50
> Why does firejail try to execute something form that folder? Avoidable? Could you fix that apparmor issue in a generic way somehow?

To clarify, `/**/*-browser/Browser/firefox` is your app AppArmor profile which blocks firejail execution. To fix it you would need to weaken this profile. This is exactly I pointed out in https://github.com/netblue30/firejail/issues/2947#issuecomment-529116717 . By trying to use both AppArmor app specific profile with firejail you decrease overall security, not improve it.

**Comment by Vincent43** [comment] 2019-09-22 15:11
Closing as it's essentially duplicate of https://github.com/netblue30/firejail/issues/2947 and makes discussion fragmented.

**Closed by Vincent43** 2019-09-22 15:11 UTC
