### ISSUE TITLE
Add a profile for prismlauncher

### ISSUE THREAD

**Issue by ipaqmaster** [netblue30/firejail#6381] opened 2024-06-13 23:00 UTC
### Description

Prismlauncher - `OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread` with firejail enabled.

### Steps to Reproduce

_Steps to reproduce the behavior_

1. Run in bash `LC_ALL=C firejail PROGRAM` (`LC_ALL=C` to get a consistent
   output in English that can be understood by everybody)
4. See error `ERROR`

### Expected behavior

_What you expected to happen_

Launch game

### Actual behavior

_What actually happened_

Did not

### Behavior without a profile

_What changed calling `LC_ALL=C firejail --noprofile /path/to/program` in a
terminal?_

Does not

### Additional context

_Any other detail that may help to understand/debug the problem_

### Environment

- Linux distribution and version (e.g. "Ubuntu 20.04" or "Arch Linux")

Arch Linux

- Firejail version (`firejail --version`).

firejail version 0.9.72

- If you use a development version of firejail, also the commit from which it
  was compiled (`git rev-parse HEAD`).

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [ ] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [ ] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

```
output goes here
```

</p>
</details>

**Comment by kmk3** [comment] 2024-06-14 08:53
Basic debugging information is missing.

What are the commands used and the profile used?

Where are the logs?

Note that there is currently no profile for this program.

**Comment by kmk3** [comment] 2024-09-14 07:07
Duplicate of #1139

**Closed by kmk3** 2024-09-14 07:07 UTC
Labels: profile-request, needinfo

**Comment by ipaqmaster** [comment] 2024-09-14 08:12
Why was the title changed on me? I didn't ask for a profile, I was having an issue making that software work with firejail.

**Comment by rusty-snake** [comment] 2024-09-14 08:20
This is the same.

> - [x] The program has a profile. (If not, request one in https://github.com/netblue30/firejail/issues/1139)

It does not has a profile.

**Comment by kmk3** [comment] 2024-09-14 09:17
If you manage to make it work, feel free to open a PR.

See also profile.template and the wiki:

* <https://github.com/netblue30/firejail/wiki/Creating-Profiles>

**Comment by ipaqmaster** [comment] 2024-09-14 09:30
Yeah ok
