### ISSUE TITLE
chromium does not work

### ISSUE THREAD

**Issue by infosisio** [netblue30/firejail#5045] opened 2022-03-14 07:18 UTC
I have tried running google-chrome with firejail google-chrome or firejail --private google-chrome and it runs fine.

Trying to do the same for chromium-browser though fails with:

```
Reading profile /etc/firejail/chromium-browser.profile
Reading profile /etc/firejail/chromium.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 633232, child pid 633233
Child process initialized in 44.23 ms
2022/03/14 09:13:44.464683 system_key.go:154: cannot determine cgroup version: cannot determine filesystem type: cannot statfs path: permission denied
```

I am on Ubuntu 20.04.

**Comment by kmk3** [comment] 2022-03-14 10:27
@infosisio commented [on Mar 14](https://github.com/netblue30/firejail/issues/5045#issue-1167982433):

> I have tried running google-chrome with firejail google-chrome or firejail
> --private google-chrome and it runs fine.
> 
> Trying to do the same for chromium-browser though fails with:
> 
> ```
> [...]
> 2022/03/14 09:13:44.464683 system_key.go:154: cannot determine cgroup version: cannot determine filesystem type: cannot statfs path: permission denied
> ```

That seems to come from here:

<https://github.com/snapcore/snapd/blob/8fc0bc71e41c91e7931d53a8820359abe923ec9e/interfaces/system_key.go#L154>

> ```golang
> 		logger.Noticef("cannot determine cgroup version: %v", err)
> ```

In which case, note that firejail is incompatible with snaps and flatpaks.

> I am on Ubuntu 20.04.

Note that when trying to install certain packages with apt, recent versions of
Ubuntu (such as on 21.10) will actually end up installing a snap instead of an
actual deb package.  See:

* #4554
* #4810

So if you are affected by this, you need to install the "real" chromium package
to use it in firejail.

You might also need to remove the chromium snap first before trying that.

Note that there are Ubuntu derivatives (such as Linux Mint) that do not do
these shenanigans; their apt should only install proper deb packages.

Closing this as a duplicate of #4962.

**Closed by kmk3** 2022-03-14 10:27 UTC
