### ISSUE TITLE
Google-chrome does not open anymore.

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#1885] opened 2018-04-12 18:13 UTC
Hi, 

I executed `sudo firecfg`, and after a reboot, I can't launch google-chrome anymore.
I'm posting with chromium, which runs fine.

```
firejail version 0.9.53

Compile time support:
	- AppArmor support is disabled
	- AppImage support is enabled
	- bind support is enabled
	- chroot support is enabled
	- file and directory whitelisting support is enabled
	- file transfer support is enabled
	- networking support is enabled
	- overlayfs support is enabled
	- private-home support is enabled
	- seccomp-bpf support is enabled
	- user namespace support is enabled
	- X11 sandboxing support is enabled
```
Distrib : Ubuntu 16.04 LTS
Google-chrome : `Google Chrome 65.0.3325.181`

```
firejail google-chrome


Reading profile /usr/local/etc/firejail/google-chrome.profile
Reading profile /usr/local/etc/firejail/chromium-common.profile
Reading profile /usr/local/etc/firejail/disable-common.inc
Reading profile /usr/local/etc/firejail/disable-devel.inc
Reading profile /usr/local/etc/firejail/disable-interpreters.inc
Reading profile /usr/local/etc/firejail/disable-programs.inc
Reading profile /usr/local/etc/firejail/whitelist-common.inc
Reading profile /usr/local/etc/firejail/whitelist-var-common.inc
Parent pid 4641, child pid 4642
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Child process initialized in 88.85 ms
Warning: an existing sandbox was detected. /usr/bin/google-chrome will run without any additional sandboxing features
/usr/bin/google-chrome: line 45: /dev/fd/62: No such file or directory
/usr/bin/google-chrome: line 46: /dev/fd/62: No such file or directory

(google-chrome:6): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(google-chrome:6): GLib-GIO-CRITICAL **: g_dbus_connection_register_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(google-chrome:6): GLib-GIO-CRITICAL **: g_dbus_connection_get_unique_name: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[6:24:0412/200611.719344:ERROR:address_tracker_linux.cc(174)] Could not bind NETLINK socket: Address already in use (98)
```

EDIT : if I `sudo firecfg --clean` and run `google-chrome` without jail, it opens google-chrome window.
EDIT2 : same issue happens with chromium when I restarted the browser.

Any idea what is going wrong ?
(I'm using nvidia proprietary drivers)

**Comment by SkewedZeppelin** [comment] 2018-04-13 15:08
if you've run firecfg then doing `firejail google-chrome` is equlivant to `firejail firejail /usr/bin/google-chrome`

assuming running `firejail /usr/bin/google-chrome` still has issues:
- commenting `noroot` is the fix for nvidia issues
- commenting `private-dev` will fix those /dev/fd errors
- the dbus errors are intended as part of `nodbus`

**Comment by flurrylol** [comment] 2018-04-14 16:25
@SkewedZeppelin : Yes, on the `firejail google-chrome` command, I had disable firecfg by executing `sudo firecfg --clean`, sorry that I didn't mention that, your assumption was good. :-) 
Adding the parameters did not help me.

@noahhaon : I don't have a firejail folder in /etc.
So I executed `./configure && make && sudo make install-strip` but still, no firejail folder in /etc.
After executing the installation command, I retried :
`firejail google-chrome` : it worked !
`sudo firecfg` +  `google-chrome` : nope, just like before.
`sudo firecfg --clean` + `firejail google-chrome` : it worked !

Browser does start with firejail command, but does not start if I launch it after firecfg.

**Comment by joeygravlin** [comment] 2018-04-18 21:45
I'm having the same `Could not bind NETLINK socket: Address already in use (98)` error on Arch Linux. At any rate, downgrading the package from `chromium-66.0.3359.117-1` - >  `chromium-65.0.3325.181-7` seems to resolve the issue on my machine.

The following chromium version segfaults both with{,out} firejail sandbox... Not sure whether this is a problem with upstream or with Arch's packaging... 

Dmesg shows `chromium-66.0.3359.117-1` segfaults both with{,out} firejail sandbox... Downgrading for the time being.

```
...
starting application
LD_PRELOAD=(null)
execvp argument 0: /usr/bin/chromium
Child process initialized in 134.37 ms
monitoring pid 9

[9:19:0418/171130.317285:ERROR:address_tracker_linux.cc(175)] Could not bind NETLINK socket: Address already in use (98)
Sandbox monitor: waitpid 9 retval 9 status 139
Sandbox monitor: monitoring 11
monitoring pid 11

Sandbox monitor: waitpid 11 retval 11 status 0

Parent is shutting down, bye...
```


Here's my current `~/.config/firejail/chromium.profile`:

```
# Firejail profile for chromium
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/chromium.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/.cache/chromium
noblacklist ${HOME}/.config/chromium
noblacklist ${HOME}/.config/chromium-flags.conf
noblacklist ${HOME}/.pki

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-programs.inc

mkdir ${HOME}/.cache/chromium
mkdir ${HOME}/.config/chromium
mkdir ${HOME}/.pki
whitelist ${DOWNLOADS}
whitelist ${HOME}/.cache/chromium
whitelist ${HOME}/.config/chromium
whitelist ${HOME}/.config/chromium-flags.conf
whitelist ${HOME}/.pki
include /etc/firejail/whitelist-common.inc
include /etc/firejail/whitelist-var-common.inc

caps.keep sys_chroot,sys_admin
netfilter
#nodbus
nodvd
nogroups
notv
shell none

disable-mnt
# private-bin chromium,chromium-browser,chromedriver
# private-dev disabled for u2f keys.
# private-dev
# private-tmp - problems with multiple browser sessions

noexec ${HOME}
noexec /tmp

# the file dialog needs to work without d-bus
#env NO_CHROME_KDE_FILE_DIALOG=1
```

**Comment by flurrylol** [comment] 2018-04-19 05:35
@joeygravlin You also have last firejail version ?
Trying to run firejail chromium (or google-chrome) still doesn't work for me with last version.
If I downgrade firejail version to 0.9.38.10, it works with last google-chrome / chromium version.

**Comment by Fred-Barclay** [comment] 2018-04-20 00:40
I'm on Arch and latest Chrome (v66.0.3359.117) and I haven't had any crashes with Chrome either in or out of firejail. Right now it does sound like the issue is with chromium, not firejail. :smile:

**Comment by joeygravlin** [comment] 2018-05-20 14:14
On my machine, problem is resolved by `mv ~/.config/chromium-flags.conf{,.bak}`, as suggested by:
[bugs.archlinux.org - FS#58269 - [chromium] crashes with: "Segmentation fault (core dumped)" on startup - #comment168669](https://bugs.archlinux.org/task/58269#comment168669)

**Comment by chiraag-nataraj** [comment] 2018-12-09 14:20
OP has left Github and it looks like other posters have resolved the issues they had.

**Closed by chiraag-nataraj** 2018-12-09 14:20 UTC
