### ISSUE TITLE
/usr/share is empty with google chrome profiles.

### ISSUE THREAD

**Issue by crocket** [netblue30/firejail#5125] opened 2022-04-30 08:36 UTC
### Description

/usr/share is empty with all google chrome profiles.

tmpfs is mounted on /usr/share.

### Environment

- Linux distribution and version: Gentoo Linux
- Firejail version (`firejail --version`).
```
firejail version 0.9.68

Compile time support:
        - always force nonewprivs support is disabled
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - D-BUS proxy support is enabled
        - file transfer support is enabled
        - firetunnel support is disabled
        - networking support is enabled
        - output logging is enabled
        - overlayfs support is disabled
        - private-home support is enabled
        - private-cache and tmpfs as user enabled
        - SELinux support is disabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled
```

**Comment by crocket** [comment] 2022-04-30 09:21
The combination of [build_share](https://github.com/netblue30/firejail/blob/9ec6288674f7473138038128c232dd198b6f509a/etc/profile-a-l/google-chrome.profile#L8-L12) in src/fbuilder/build_fs.c and [etc/profile-a-l/google-chrome.profile](https://github.com/netblue30/firejail/blob/9ec6288674f7473138038128c232dd198b6f509a/etc/profile-a-l/google-chrome.profile#L8-L12) led to empty /usr/share.

**Comment by rusty-snake** [comment] 2022-04-30 11:29
Duplicate of #4929

**Comment by rusty-snake** [comment] 2022-04-30 11:29
Duplicate of #4965

**Comment by rusty-snake** [comment] 2022-04-30 11:30
Fixed by 56ebc8ac984a8fc6f4470ab507f7bc0fd3720bbd

**Comment by rusty-snake** [comment] 2022-04-30 11:30
> `filedb_print(share_out, "whitelist /usr/share/", fp);` in [src/fbuilder/build_fs.c](https://github.com/netblue30/firejail/blob/9ec6288674f7473138038128c232dd198b6f509a/src/fbuilder/build_fs.c#L341-L343)

If you use a custom profile you should post it.

**Comment by crocket** [comment] 2022-04-30 23:05
I didn't use a custom profile.

**Comment by rusty-snake** [comment] 2022-05-01 07:49
> I didn't use a custom profile.

Why did you referenced fbuilder then? `filedb_print(share_out, "whitelist /usr/share/", fp);` is only executed if you build a custom profile.

> This issue is not a duplicate of either https://github.com/netblue30/firejail/issues/4929 or https://github.com/netblue30/firejail/issues/4965

chrom* has issues with firejail 0.9.68 because of empty /usr/share. Sounds very close.

> My suggested solution to this issue is to remove ignore include whitelist-usr-share-common.inc in google chrome profiles. It's okay to remove ignore include whitelist-runuser-common.inc, too.

If you tested this, open a PR. The only reason why they are disabled is that no-one has tested so far.

> When /usr/share is empty, google chrome has various issues.

https://github.com/netblue30/firejail/issues/4929 or https://github.com/netblue30/firejail/issues/4965

> By the way, https://github.com/netblue30/firejail/commit/56ebc8ac984a8fc6f4470ab507f7bc0fd3720bbd doesn't fix the issue.

Can you follow the issue template. Mainly `--noprofile`, the checklist and log output.

Reopening for now.

**Comment by crocket** [comment] 2022-05-01 12:35
By the way, what is a custom profile? I just used /etc/firejail/google-chrome.profile.

**Comment by rusty-snake** [comment] 2022-05-01 12:45
Any profile you create/edit by hand in an editor or generated with a program/script. i.e. every profile not included in your firejail installation package.

**Closed** 2022-05-12 12:42 UTC
Labels: duplicate, notabug
