### ISSUE TITLE
"Firefox is not currently set as your default browser"

### ISSUE THREAD

**Issue by BafDyce** [netblue30/firejail#1355] opened 2017-06-28 13:22 UTC
When running firefox via firejail, it displays a notice "Firefox is not currently set as your default browser. Would you like to make it your default browser?" on startup. No matter what I click on that dialog, the very same dialog apears at every launch.

This happens on two different systems:
* Fedora with Gnome
* Ubuntu 16.04 with Gnome

On both machines, Firefox was set as the default browser prior to installing firejail.

As a side note: The settings page says "Firefox is not your default browser", however clicking on the "Make default" button changes nothing. Is this a known limitation (I couldn't find any issue addressing this), a configuration error on my side, or a bug?

**Comment by SpotComms** [comment] 2017-06-28 14:42
I can confirm this happens. It is due to two issues:
- Firefox creates a copy of .config/mimeapps.list, then it edits it, and it moves it in place of the original.
  - This should work as it has rw of that file, but fails for some reason
- Firefox then runs "update-mime-database"
  - This fails as .local/share/mime isn't included in the profile

As a workaround you can manually set it through Settings > Details > Default Applications in Gnome

**Comment by netblue30** [comment] 2017-06-28 16:10
If we just whitelist ~/.local/share/mime and ~/config/mimeapps.list, would it fix it?

**Comment by BafDyce** [comment] 2017-06-28 16:11
> * Firefox creates a copy of .config/mimeapps.list, then it edits it, and it moves it in place of the original.
>     * This should work as it has rw of that file, but fails for some reason

Looking at firefox.profile, I cannot find a whitelist entry for that file

> * Firefox then runs "update-mime-database"
>    * This fails as .local/share/mime isn't included in the profile

Would it be acceptable to include it into the profile?

> As a workaround you can manually set it through Settings > Details > Default Applications in Gnome

Firefox is set as the default browser there :/

**Comment by BafDyce** [comment] 2017-06-28 16:12
@netblue30 
 I can test it, if you want.

**Comment by netblue30** [comment] 2017-06-28 16:12
Thanks, give it a try.

**Comment by BafDyce** [comment] 2017-06-28 16:39
I added the following rules to my profile:

```
<block of noblacklist lines>
noblacklist ~/.config/mimeapps.list
noblacklist ~/.local/share/mime

...

<block of whitelist lines>
whitelist ~/.config/mimeapps.list
whitelist ~/.local/share/mime
```

However, I still get errors when trying to set firefox as the default browser (via the button in the preferences tab):
```
** (firefox:5): WARNING **: Cannot set application as default for URI scheme (http): Failed to rename file '/home/user/.config/mimeapps.list.EKLK2Y' to '/home/user/.config/mimeapps.list': g_rename() failed: Device or resource busy
```

lsof (run from the host, outside the jail) doesn't report the file as opened by another application.

Any idea why it still doesn't work?

**Comment by SpotComms** [comment] 2017-06-28 16:49
.config/mimeapps.list is already whitelisted through whitelist-common.inc

and like I said its weird, it should be able to write edit .config/mimeapps.list

You can do manual testing using "firejail --profile=/etc/firejail/firejail.profile /bin/bash"

**Comment by smitsohu** [comment] 2017-07-15 00:19
Another workaround: Uncomment `private-bin` in the Firefox profile

**Comment by smitsohu** [comment] 2017-07-15 11:25
The error message corresponds to the EBUSY error of rename(), I guess it has something to do with mimeapps.list being a mount point. When whole ~/.config is whitelisted, the issue seems to disappear.

**Comment by smitsohu** [comment] 2017-09-13 15:33
~/.config/mimeapps.list is a mount point (it is explicitly whitelisted), and the issue is that we cannot run rename() on a mount point. 
If instead the whole ~/.config is whitelisted, everything works again as expected.

I observe the same with KDE apps that make use of KConfig, because the mechanism is similar... also there whitelisting of configuration files effectively freezes the settings, because the renaming fails.

**Comment by chiraag-nataraj** [comment] 2018-07-22 19:50
I think there are enough workarounds in the thread that we can close the issue.

**Closed by chiraag-nataraj** 2018-07-22 19:50 UTC
Labels: information
