### ISSUE TITLE
Fix electrum profile

### ISSUE THREAD

**Issue by ubone** [netblue30/firejail#3085] opened 2019-12-16 15:48 UTC
```
$ firejail --profile=electrum --appimage ./electrum-3.3.8-x86_64.AppImage
Reading profile /etc/firejail/electrum.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Error: cannot configure loopback device

$ firejail --noprofile --appimage electrum-3.3.8-x86_64.AppImage
Error: cannot configure loopback device

$ firejail --version
firejail version 0.9.60

Compile time support:
        - AppArmor support is enabled
        - AppImage support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

$ distro
Name: Arch Linux
```

please

**Comment by rusty-snake** [comment] 2019-12-16 16:02
LOG: electrum-3.3.4 works, therefore the issue is with version 3.3.5 or with appimage.

**Comment by glitsj16** [comment] 2019-12-16 18:16
@ubone Electrum 3.3.8 is in the [official](https://www.archlinux.org/packages/community/any/electrum/) Arch community repo and works just fine with firejail for me. I recommend using that instead of the appimage if you want to firejail it. Any reason why you are opting for the latter instead?

**Comment by ubone** [comment] 2019-12-17 07:06
@glitsj16 just trying stuff but that's beside the point since i used `--appimage`

**Comment by akoun** [comment] 2019-12-28 18:31
> @glitsj16 just trying stuff but that's beside the point since i used `--appimage`
I agree.
For your information I had the same problem with another appimage and it worked once I used the --private option; E.g. 
firejail --private=./tmp --appimage ./AppImages/MyPaint-v2.0.0-beta.0-12-g53b1cc8-2019-12-26_08.28.AppImage

**Comment by glitsj16** [comment] 2019-12-29 00:24
@akoun I'll fix @ubone's issue, which relates to `private-dev`. But I would strongly advise against using private/private= for a Bitcoin wallet, as those options will discard all modifications when the sandbox is closed. Modifications in this context would be whatever coins are in the wallet I assume.

@ubone Can you try adding the below in `electrum.local` (either in /etc/firejail or in your ${HOME}/.config/firejail) and test again please?

`?HAS_APPIMAGE: ignore private-dev`

**Comment by glitsj16** [comment] 2019-12-29 06:02
Fixed in git master via https://github.com/netblue30/firejail/commit/cb1a17400567eefdc2e37e630d9490b84e7fc1ef. I'll close this as soon as @ubone confirms this fixes the reported issue.

**Comment by ubone** [comment] 2019-12-29 07:24
```
$ firejail --profile=electrum --appimage ./electrum-3.3.8-x86_64.AppImage
Reading profile /etc/firejail/electrum.profile
Reading profile /home/ubone/.config/firejail/electrum.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Error: cannot configure loopback device
$ more /home/ubone/.config/firejail/electrum.local
?HAS_APPIMAGE: ignore private-dev
```

**Comment by glitsj16** [comment] 2019-12-29 08:42
@ubone Thanks for the feedback. I have downloaded the appimage and for me it works just fine with firejail from git (see below). So it must be something in firejail 0.9.60 that's causing your issue. Did you change anything in /etc/firejail/firejail.config?

Let's try using the default.profile running the below command:

`$ firejail --appimage electrum-3.3.8-x86_64.AppImage`

Alternatively you can use the [firejail-git](https://aur.archlinux.org/packages/firejail-git/) package from the AUR.

```
$ firejail --profile=electrum --appimage electrum-3.3.8-x86_64.AppImage
Reading profile /etc/firejail/electrum.profile
Reading profile /etc/firejail/allow-python2.inc
Reading profile /etc/firejail/allow-python3.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Mounting appimage type 2
Parent pid 426667, child pid 426670


**     Warning: dropping all Linux capabilities     **

Warning: skipping alternatives for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Private /etc installed in 91.72 ms
Child process initialized in 504.72 ms
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by ubone** [comment] 2019-12-29 10:57
huh now it's something else (0.9.60):

```
$ firejail --appimage electrum-3.3.8-x86_64.AppImage
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: Invalid argument

$ firejail --profile=electrum --appimage electrum-3.3.8-x86_64.AppImage
Reading profile /etc/firejail/electrum.profile
Reading profile /home/ubone/.config/firejail/electrum.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Mounting appimage type 2
Error mounting appimage: appimage.c:122 appimage_set: Invalid argument
```

git (r5763.cb1a1740-1):

```
$ firejail --appimage electrum-3.3.8-x86_64.AppImage
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 146826, child pid 146829

**     Warning: dropping all Linux capabilities     **

Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 181.86 ms
Traceback (most recent call last):
  File "/run/firejail/appimage/.appimage-146826/usr/bin/electrum", line 358, in <module>
    fd, server = daemon.get_fd_or_server(config)
  File "/run/firejail/appimage/.appimage-146826/usr/lib/python3.6/site-packages/electrum/daemon.py", line 77, in get_fd_or_server
    remove_lockfile(lockfile)
  File "/run/firejail/appimage/.appimage-146826/usr/lib/python3.6/site-packages/electrum/daemon.py", line 58, in remove_lockfile
    os.unlink(lockfile)
PermissionError: [Errno 13] Permission denied: '/home/ubone/.electrum/daemon'

Parent is shutting down, bye...
AppImage unmounted
```


git works (r5763.cb1a1740-1):

```
$ firejail --profile=electrum --appimage electrum-3.3.8-x86_64.AppImage
Reading profile /etc/firejail/electrum.profile
Reading profile /home/ubone/.config/firejail/electrum.local
Reading profile /etc/firejail/allow-python2.inc
Reading profile /etc/firejail/allow-python3.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Mounting appimage type 2
Parent pid 146879, child pid 146882

**     Warning: dropping all Linux capabilities     **

Warning: skipping alternatives for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Private /etc installed in 62.44 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 309.28 ms
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: image driver extension not found
libGL error: failed to load driver: radeon

Parent is shutting down, bye...
AppImage unmounted
```

idk if it's an outdated profile or firejail itself but it works so i guess it's a non issue

**Comment by glitsj16** [comment] 2019-12-29 14:58
> Error mounting appimage: appimage.c:122 appimage_set: Invalid argument

I've seen that exact same issue with other non-firejail applications recently. My guess is this is due to the changes in libfuse (fuse2 and fuse3 packages on Arch). Is your system fully updated? Bad mirror or something? In any case, I don't think this is a firejail issue.

> $ firejail --appimage electrum-3.3.8-x86_64.AppImage
> ...
> PermissionError: [Errno 13] Permission denied: '/home/ubone/.electrum/daemon'

Probably fixable by running
$ firejail noblacklist ${HOME}/.electrum --appimage electrum-3.3.8-x86_64.AppImage

> $ firejail --profile=electrum --appimage electrum-3.3.8-x86_64.AppImage

Glad you got it working. These libGL errors are not unusual and shouldn't interfere with electrum's performance IMHO.

I'll close this, but do feel free to reopen if you notice anything fishy during usage of the application. Thanks for reporting this and your efforts to provide feedback!

**Closed by glitsj16** 2019-12-29 14:58 UTC
