### ISSUE TITLE
Various issues with building RPM files

### ISSUE THREAD

**Issue by jgriffiths** [netblue30/firejail#296] opened 2016-02-15 21:47 UTC
Currently:

- There are 2 scripts to build rpms
- mkrpm.sh is completely broken and contains committed merge conflicts
- Both scripts are overly verbose
- Both scripts duplicate data held elsewhere (version, changelog) and so will always be out of date
- Both scripts fail to cleanup if interrupted
- The spec file is missing a library

The rpm building really should be/needs to be simplified and added to the make machinery.

**Comment by h1z1** [comment] 2016-02-16 03:14
See  #238 .  I believe they are working on it.

**Comment by jgriffiths** [comment] 2016-02-16 03:35
@h1z1 That issue isn't directly related although they obviously had issues with the RPM creation in 0.9.38 as shown by their comments about e.g. needing to add the the missing library to the spec file. The patch that closed that issue didn't touch the rpm creation scripts or the spec file at all.

The 0.9.39/HEAD rpm creation script has a merge conflict checked into it and cannot be run. Even if it was fixed and could be run, the spec file is currently incorrect. If that is fixed, the procedure to create an rpm is manual, laborious and error prone. In addition every time the current version or RELNOTES is changed the rpm script will need to be manually updated. This issue and associated pull request are to fix those problems.

**Comment by netblue30** [comment] 2016-02-16 13:50
https://github.com/netblue30/firejail/issues/238 - there was a problem with 0.9.38 on CentOS 6, /run directory does not exist on Centos 6, the user would have to create it manually. The problem is fixed now. I'll go ahead and merge https://github.com/netblue30/firejail/pull/297

**Comment by netblue30** [comment] 2016-02-16 15:36
All merged, thanks!

**Closed by netblue30** 2016-02-16 15:36 UTC
Labels: information
