### ISSUE TITLE
Firejail breaks gajim

### ISSUE THREAD

**Issue by qazip** [netblue30/firejail#2209] opened 2018-10-20 18:56 UTC
Using latest version of firejail. Here's the output of 'gajim':

```
➜  ~ gajim                                                                                                                    
Reading profile /etc/firejail/gajim.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 28273, child pid 28274
Warning: skipping alsa for private /etc
Warning: skipping crypto-policies for private /etc
Warning: skipping pki for private /etc
Private /etc installed in 35.31 ms
10 programs installed in 11.73 ms
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Child process initialized in 125.34 ms
execvp: No such file or directory

Parent is shutting down, bye...
```

**Comment by Fred-Barclay** [comment] 2018-10-20 19:00
I can't replicate on Arch. What distro and version of gajim are you using?
Cheers!

**Comment by qazip** [comment] 2018-10-21 09:31
@Fred-Barclay, why would you not be able to replicate? Can you provide your gajim profile and both versions of your firejail and gajim?

**Comment by Fred-Barclay** [comment] 2018-10-21 18:43
I don't know. :confused: I've build firejail from yesterday's commit (7c481eb43c3a737eeb5a0e4fc089efa281549e4c) so my profile is https://github.com/netblue30/firejail/blob/92bff8a23c8d7eb89c9bc1c1f9c8a74f74524fc2/etc/gajim.profile

**Comment by SkewedZeppelin** [comment] 2018-10-21 18:58
I too cannot reproduce under firejail from master with gajim 1.0.3

You might have a broken install of python or something under Antergos, have you fully updated recently?
`sudo pacman -Syyuu`

**Comment by qazip** [comment] 2018-10-22 08:50
That is weird. I have everything properly updated. I tried running with that profile and it still doesn't run. Though it runs with --noprofile. What exactly does --noprofile do? Later I will try commenting line by line, to see where it breaks..

**Comment by qazip** [comment] 2018-10-22 10:37
So, I found out that commenting `#private-bin python,python3,sh,gpg,gpg2,gajim` makes it work. Any idea why?

**Comment by smitsohu** [comment] 2018-10-30 11:11
If you run `firejail --build gajim` and then close the program again, there should be a line with private-bin.

Does it contain something that is not yet in the profile?

**Comment by cron0mat** [comment] 2018-10-31 16:05
I can confirm the same error on **Ubuntu 18.10** with 

Gajim 1.1.0 beta1-1 and
firejail 0.9.56-1 ubuntu18.10.0

Commenting private-bin as above mentioned makes gajim work again.

**Comment by Gronkdalonka** [comment] 2018-11-12 10:12
Same for me on Debian stretch with
Gajim 1.1.0-beta2-1
Firejail 0.9.56-2

Seems only to be a problem though if apparmor is enabled.
private-bin workaround is working here as well.

**Comment by rusty-snake** [comment] 2018-12-27 13:59
I had the same problem. (F29, Gajim 1.0.3)

See #2313. Does  ceb47b1 work for everyone?

**Comment by rusty-snake** [comment] 2018-12-28 21:49
If this works for all, we can close here.

**Comment by rusty-snake** [comment] 2019-04-10 16:18
Closing here, feel free to reopen.

**Closed by rusty-snake** 2019-04-10 16:18 UTC
