### ISSUE TITLE
vscode source control adding remote error

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [netblue30/firejail#5138] opened 2022-05-11 14:55 UTC
When trying to add a github remote in vscode - source control, I got a pop up error saying "Unknown error code 100
The program 'firejail' was found at '/usr/bin/firejail' but it is missing executable permissions."

firejail version : 0.9.68

**Comment by kmk3** [comment] 2022-05-11 15:22
@GreatBigWhiteWorld commented [on May 11](https://github.com/netblue30/firejail/issues/5138#issue-1232787579):

> When trying to add a github remote in vscode - source control, I got a pop up
> error saying "Unknown error code 100 The program 'firejail' was found at
> '/usr/bin/firejail' but it is missing executable permissions."
> 
> firejail version : 0.9.68

There is a lot of relevant information missing; please follow the bug report
template:

<https://github.com/netblue30/firejail/issues/new?assignees=&labels=&template=bug_report.md&title=>

Also, what is the output of:

```sh
ls -l /usr/bin/firejail
```

**Comment by GreatBigWhiteWorld** [comment] 2022-05-12 03:37
I narrowed down the issue to that "whenever vscode wants to open a link in a browser, it pops up the above message". 

`
ls -l /usr/bin/firejail
-rwsr-x--- 1 root firejail 466576 Mar  2 00:08 /usr/bin/firejail
`

**Comment by rusty-snake** [comment] 2022-06-08 11:55
> There is a lot of relevant information missing; please follow the bug report template:
>
> https://github.com/netblue30/firejail/issues/new?assignees=&labels=&template=bug_report.md&title=

You still did provided basic important information in your bug report. Closing as what it looks like.

Duplicate of #3604

**Closed by rusty-snake** 2022-06-08 11:55 UTC
