### ISSUE TITLE
[firefox] `noroot` makes youtube fullscreen hang

### ISSUE THREAD

**Issue by Saren-Arterius** [netblue30/firejail#1771] opened 2018-02-09 16:36 UTC
Test scenerio:
https://www.youtube.com/watch?v=1La4QzGeaaQ&t=60s
Select 4k60 and go fullscreen, the video could play for few seconds, then firefox freezed that had to be killed. Without the setting `noroot` (discovered by trial and error), then video plays just fine.

OS/Software/Drivers:
Arch Linux
firefox 58.0.2-1
firejail 0.9.52-1
linux 4.15.1-2
nvidia-dkms 390.25-4

**Comment by SkewedZeppelin** [comment] 2018-02-09 17:19
Duplicate of #1753.
Quick and easy fix it to either switch to nouveau or `echo "ignore noroot" >> /etc/firejail/globals.local`

**Closed by SkewedZeppelin** 2018-02-09 17:19 UTC

**Comment by idnovic** [comment] 2018-03-05 16:52
I have issues to but with intel.
I can play variable time of an video but at on point it just freezes until I unfullscrenn the video.
The moment I unfullscreen it the playback goes on. I can now put it in fullscreenmode again.

I added the suggested fix but the problem persists.
