### ISSUE TITLE
Pentadactylrc file is emptied

### ISSUE THREAD

**Issue by Eisfreak7** [netblue30/firejail#183] opened 2015-12-04 20:42 UTC
Whenever I launch firejail with the firefox profile, my ~/.pentadacylrc file gets emptied (even if I just launch a shell instead of firefox). So for example:
```
echo "test" > ~/.pentadactylrc
firejail --profile=~/.config/firejail/firefox.profile
# in another shell (or after exiting firejail):
cat ~/.pentadactylrc # returns nothing, as the file is now empty
```

As far as I can tell this happens only with the pentadactylrc file. If I create a file called ~/testfile with some text in it and include it in the whitelist of the profile, that file doesn't get emptied.  
I know this probably isn't enough info to tell what's causing this, but this is such a weired behaviour and I don't know what else might be helpful.

**Comment by netblue30** [comment] 2015-12-04 21:15
I think I have it fixed on the master branch. You need to add the following two lines to your firefox.profile file:
`````
whitelist ~/.pentadactylrc
whitelist ~/.pentadactyl
`````

**Comment by Eisfreak7** [comment] 2015-12-04 21:48
Those lines are already there. Here's the complete profile (it should be pretty much identical with the default one):
```
# Firejail profile for Mozilla Firefox (Iceweasel in Debian)
noblacklist ${HOME}/.mozilla
include /etc/firejail/disable-mgmt.inc
include /etc/firejail/disable-secret.inc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
caps.drop all
seccomp
protocol unix,inet,inet6
netfilter
noroot
whitelist ~/.mozilla
#whitelist ~/Downloads
whitelist ~/.gtkrc-2.0
whitelist ~/.vimperatorrc
whitelist ~/.vimperator
whitelist ~/.pentadactylrc
whitelist ~/testfile
whitelist ~/.pentadactyl

# common
whitelist ~/.fonts
whitelist ~/.fonts.d
whitelist ~/.fontconfig
whitelist ~/.fonts.conf
whitelist ~/.fonts.conf.d
```
I haven't testet it withe the version from the master branch yet though (I'm running version 0.9.34). I'll do that tomorrow.

**Comment by Eisfreak7** [comment] 2015-12-05 08:01
It still happens on the latest git version. The same profile, the same pentadactylrc, still empty.

**Comment by netblue30** [comment] 2015-12-06 13:03
I am not able to reproduce it:
`````
$ echo "test" > ~/.pentadactylrc
$ firejail --profile=/etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 3791, child pid 3792
Child process initialized
$ cat ~/.pentadactylrc
test
$ exit
exit

parent is shutting down, bye...
$ cat ~/.pentadactylrc
test
$ 
`````

**Comment by Eisfreak7** [comment] 2015-12-08 12:25
For me, nothing has changed. I tried using the default firefox profile (the only thing I had changed was commenting out the Downloads directory, because it is symlinked to another hdd and firejail complains), but that gives the same results. Executing the exact same commands as you do after a fresh git build (firejail-git from the AUR):
```
$ echo "test" > ~/.pentadactylrc
$ firejail --profile=/etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Warning: user namespaces not available in the current kernel.
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 30144, child pid 30145
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized
$ cat ~/.pentadactylrc
$ exit
exit

parent is shutting down, bye...
$ cat ~/.pentadactylrc
$ 
```

Interestingly, even if I write something in the pentadactylrc file when in the firejail, it stays empty:
```
$ firejail --profile=/etc/firejail/firefox.profile
Reading profile /etc/firejail/firefox.profile
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Warning: user namespaces not available in the current kernel.
Reading profile /etc/firejail/whitelist-common.inc
Parent pid 30144, child pid 30145
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Blacklist violations are logged to syslog
Child process initialized
$ echo "test" > ~/.pentadactylrc
$ cat
```

**Comment by netblue30** [comment] 2015-12-08 21:33
If ~/.pentadactylrc does not exist before you start the sandbox, the file will not get whitelisted. Files not whitelisted, or files in directories not whitelisted will be discarded when you exit the sandbox. I would say run firefox without the sandbox, so ti will create ~/.pentadactylrc, and next time when you start the sandbox the file will be preserved.

**Comment by Eisfreak7** [comment] 2015-12-09 06:56
But the file does exists. I'm typing this in firefox with pentadactyl. And as I wrote in my previous posts, I even tried creating a dummy pentadactylrc (`echo test > ~/.pentdadactylrc`) before starting the sandbox (because I thought my pentadactylrc being symlinked might be the problem, which it apparently is not).

**Comment by netblue30** [comment] 2015-12-10 13:15
I'll have to look into it, so far I couldn't reproduce it. Thanks.

**Comment by netblue30** [comment] 2015-12-29 18:21
Can you please retest it on version 0.9.36. Thanks!

**Comment by netblue30** [comment] 2015-12-29 18:22
I'll reopen the bug if necessary.

**Closed by netblue30** 2015-12-29 18:21 UTC
Labels: bug

**Comment by Eisfreak7** [comment] 2015-12-30 12:29
The first frew tries didn't work. But I can't reproduce that so I guess I must have made a mistake.
But now it works fine, thank you :)

The remaining problem (its not really a problem for me, but I guess it isn't intentional) is:
When I symlink my `.pentadactylrc` to another file `symlink` and whitelist *both* files, the pentadactylrc still gets emptied. However when I just whitelist one of the files it works.  
Thats not the same problem as before, because before it didn't work at all (even without symlinks).

Also not sure if it is intended but I think its a bit odd that symlinks inside whitelisted directories have to be whitelisted sperately in order to work. But that could as well be intended, I just wanted to point  that out in case it isn't.

Thanks for your work!
