### ISSUE TITLE
slack-desktop 4.4.3 not starting

### ISSUE THREAD

**Issue by nackd** [netblue30/firejail#3477] opened 2020-06-24 14:56 UTC
Slack is failing to start with no visible error message.

`firejail --ignore=seccomp slack` works, though.

**Environment**
 - Up to date Archlinux
 - Firejail 0.9.62

**Comment by rusty-snake** [comment] 2020-06-24 15:27
Duplicate of #3015

**Comment by rusty-snake** [comment] 2020-06-24 15:27
Duplicate of #3003

**Comment by rusty-snake** [comment] 2020-06-24 15:27
Duplicate of #2866

**Comment by rusty-snake** [comment] 2020-06-24 15:27
Duplicate of #2946

**Comment by rusty-snake** [comment] 2020-06-24 15:28
> firejail --ignore=seccomp slack works, though.

Add it to your slack.local and wait for the the firejail release. It should already be fixed on master.

**Comment by nackd** [comment] 2020-06-24 15:56
I copied the changes to slack.profile and the new disable-shell.inc from master to my 0.9.62 install and it works without having to deactivate seccomp. Feel free to close. Thank you!

**Closed** 2020-06-24 15:57 UTC
Labels: duplicate
