### ISSUE TITLE
Disable noroot at chrom* (including iridium and inox flavours)

### ISSUE THREAD

**Issue by bn0785ac** [netblue30/firejail#1678] opened 2017-12-13 18:58 UTC
Affected profiles:

* Inox

* Bnox

* Dnox

* Iridium

* Chromium

* Google chrome Stable

* Google Chrome Beta

* Google Chrome Dev

Bugfix

remove noroot

**Comment by bn0785ac** [comment] 2017-12-13 18:58
Its a linux 4.14.5+ bug

**Comment by SpotComms** [comment] 2017-12-13 19:08
What is wrong? And what is the Linux bug?

**Comment by bn0785ac** [comment] 2017-12-13 21:15
@SpotComms  i got this run error with norrot
https://p.teknik.io/Yzrjo

**Comment by SpotComms** [comment] 2017-12-13 21:44
I cannot reproduce this issue on either 4.14.3 or 4.14.5. Are you running under root?

**Comment by bn0785ac** [comment] 2017-12-13 22:37
no, i'm at normal user

**Comment by smitsohu** [comment] 2018-03-05 14:11
Closing for now, as there is no `noroot` in mainline profiles.

**Closed by smitsohu** 2018-03-05 14:11 UTC
