### ISSUE TITLE
Firefox exit code question

### ISSUE THREAD

**Issue by reinerh** [netblue30/firejail#1947] opened 2018-05-17 20:55 UTC
A Debian user of firejail [reported](https://bugs.debian.org/898891) that since 0.9.54 he observes a different exit status (1 instead of 0) when opening new tabs in Firefox (ESR 52) with `firejail --name=firefox firefox-esr $url` (when an instance is already running).

As I can't reproduce that behavior on my machine, I'm curious if other users are seeing this issue too.
Could someone please try it out as well?

**Comment by SkewedZeppelin** [comment] 2018-05-17 21:32
I was unable to reproduce under the following

Firefox 60 on Arch
Firefox ESR 60.0.1 on Arch
Firefox 60 on Fedora 28
Icecat 52.7.3 on Fedora 28

and I did indeed test by first launching an instance and then passing a URL the second time

**Comment by netblue30** [comment] 2018-05-19 17:26
I'm not seeing it on my computers also.

**Comment by reinerh** [comment] 2018-05-30 20:27
@chiraag-nataraj that is interesting. when you run it the second time without firejail, does it then exit with 0 or also with 1?

**Comment by chiraag-nataraj** [comment] 2018-05-30 20:44
It repeatedly gives me 0 no matter how many times I run it or how I interleave it with `firejail` runs (the `firejail` runs similarly give me 1 no matter how many times I run it or how I interleave it with regular runs).

**Comment by reinerh** [comment] 2018-05-30 20:58
@chiraag-nataraj which distribution are you using? is `which firefox` a binary or a shell script that is starting firefox?

**Comment by chiraag-nataraj** [comment] 2018-05-30 21:03
I'm on Debian Sid. `which firefox` is `/usr/bin/firefox`, which is a symlink to `/usr/lib/firefox/firefox`, which is a binary.

**Comment by chiraag-nataraj** [comment] 2018-06-03 19:19
@reinerh I'll experiment and report back :blush:

**Comment by chiraag-nataraj** [comment] 2018-06-03 19:26
Wait, what the hell. I'm now getting 0 as expected. This is really bizarre.

**Comment by chiraag-nataraj** [comment] 2018-06-03 19:28
I suspect this may have to do with the fact that I upgraded firefox in the interim. Going to check some things and report back.

**Comment by chiraag-nataraj** [comment] 2018-06-03 19:31
Okay, I give up. This had nothing to do with the firefox upgrade and I'm now consistently getting 0 as the return value no matter what I do... :question::question::question:

**Comment by reinerh** [comment] 2018-06-03 19:34
@chiraag-nataraj okay, interesting.
thanks for trying it!

**Comment by chiraag-nataraj** [comment] 2018-10-03 05:02
I think we're not going to be able to solve this, since none of us are able to replicate. I'm going to close this for now. If it comes up again, we can re-open.

**Closed by chiraag-nataraj** 2018-10-03 05:02 UTC
Labels: bug
