### ISSUE TITLE
Firejail Configuration Wizard - readability issue (light grey text on white background)

### ISSUE THREAD

**Issue by mikewesten** [netblue30/firejail#4945] opened 2022-02-14 20:39 UTC
Needs configurable theme/color scheme options for the GUI

Add the ability to do so

Alternative option is to change my entire system to suit this one app

If possible, explain the cause and offer (hopefully) a simple solution that could've been overlooked on the user's end

System in question is Linux with Cinnamon desktop, GTK theme

screenshot of the issue:
![Screenshot from 2022-02-14 12-34-57](https://user-images.githubusercontent.com/73662866/153942552-3ae67e9c-e3a3-4fe7-9473-cd0e1af67b39.png)

**Comment by rusty-snake** [comment] 2022-02-14 20:49
Duplicate of https://github.com/netblue30/firetools/issues/51

**Closed by rusty-snake** 2022-02-14 20:49 UTC
