### ISSUE TITLE
Chromium private exposes user home directory

### ISSUE THREAD

**Issue by finkandreas** [netblue30/firejail#5303] opened 2022-08-09 09:55 UTC
I am starting `firejail --private chromium` and then go to `chrome://settings/downloads` and click on the `Change` button to change the location. A folder-selector dialog pops up, where I can see my real home directory and not the private one.
I would expect that the home directory is the temporary private one, and not the original host home directory.

**Comment by rusty-snake** [comment] 2022-08-09 15:41
Duplicate of #5246

**Closed by rusty-snake** 2022-08-09 15:41 UTC
Labels: duplicate
