### ISSUE TITLE
"Could not access secret storage"

### ISSUE THREAD

**Issue by CocoR55** [netblue30/firejail#4890] opened 2022-02-02 13:20 UTC
On the site, you can find these lines:
"Tutanota desktop app uses system keychain to be able to encrypt sensitive details such as credentials and alarms. On Linux there must be an app installed which provides secret storage (org.freedesktop.secrets interface). This is usually set up together with the rest of the desktop environment but sometimes it requires manual setup. Installing GNOME Seahorse and configuring keychain there should be sufficient. KeePassXC is another provider which can be used but it must be additionally configured."

I don't understand which key is meant? Is it the Linux password? Is it the tutanota site password?

Is it up to me to enter this key or is it automatic?

Do I have to configure Seahorse in a special way?

It's far from clear to me...

Can you please enlighten me?
Regards,
CocoR55

**Comment by rusty-snake** [comment] 2022-02-02 13:36
Duplicate of https://github.com/netblue30/firejail/issues/4627#issuecomment-947866726

**Comment by rusty-snake** [comment] 2022-02-02 13:37
Answered in https://github.com/netblue30/firejail/issues/4627#issuecomment-947922069

**Comment by AIGeneratedUsername** [comment] 2023-03-23 15:42
I confirm that creating a local profile with the following content
```
ignore dbus-user none
dbus-user filter
dbus-user.talk org.freedesktop.secrets
```
and running
```bash
firejail --profile=/etc/firejail/tutanota-desktop.local --appimage /opt/tutanota-desktop-linux.AppImage
```
successfully starts the program.

---

I am not the issue creator, but I think this issue can be closed.

**Closed** 2023-03-23 16:09 UTC
Labels: duplicate
