### ISSUE TITLE
firejail-default apparmor profile breaks code-oss

### ISSUE THREAD

**Issue by njfox** [netblue30/firejail#2538] opened 2019-03-07 21:02 UTC
`code`/`code-oss` does not work in firejail with `apparmor` support enabled. It looks like it's trying to open something with `w` permissions when it launches and is getting denied. Here are the entries in `/var/log/audit/audit.log` when trying to launch `code` in firejail:

```
type=AVC msg=audit(1551992530.121:191): apparmor="DENIED" operation="open" profile="firejail-default" name="/proc/17/comm" pid=9178 comm="electron" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000
type=SYSCALL msg=audit(1551992261.059:189): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7acf5722b140 a2=80001 a3=0 items=0 ppid=8641 pid=8658 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=2 comm="electron" exe="/usr/lib/electron/electron" subj==firejail-default (enforce) key=(null)
type=PROCTITLE msg=audit(1551992261.059:189): proctitle=2F7573722F6C69622F656C656374726F6E2F656C656374726F6E202D2D756E6974792D6C61756E6368202F7573722F6C69622F636F64652F636F64652E6A73
```
I've also confirmed `apparmor` is the problem by launching the application with the default `code.profile` without apparmor, and it works fine. Does anyone have any ideas on how to troubleshoot?

**Comment by Vincent43** [comment] 2019-03-07 22:20
You may try to add `/proc/@{PID}/comm w,` in `/etc/apparmor.d/local/firejail-local`.

**Comment by njfox** [comment] 2019-03-07 22:24
That worked, thanks!

**Comment by rusty-snake** [comment] 2019-04-20 16:44
Closing here because the issue is solved.

Additional: echoing @njfox question
> Is this something that should be considered for the default firejail apparmor policy?

**Closed by rusty-snake** 2019-04-20 16:44 UTC
