### ISSUE TITLE
Is it possible to blacklist all the .txt files recursively under a directory?

### ISSUE THREAD

**Issue by YorkZ** [netblue30/firejail#5617] opened 2023-01-25 12:31 UTC
### Discussed in https://github.com/netblue30/firejail/discussions/5616

<div type='discussions-op-text'>

<sup>Originally posted by **YorkZ** January 24, 2023</sup>
In Bash filename expansion, if `globstar` is on by:

``` shell
shopt -s globstar
```

`**` can be used to match all the files recursively.

Would it be possible to blacklist all the `.txt` files recursively similarly, by something like:

    blacklist /path/to/foo/**/*.txt

?
</div>

**Comment by kmk3** [comment] 2023-01-25 14:26
Duplicate of #5616

**Closed by kmk3** 2023-01-25 14:26 UTC
Labels: duplicate
