### ISSUE TITLE
Running xpdf in friejail

### ISSUE THREAD

**Issue by domivogt** [netblue30/firejail#3975] opened 2021-02-11 19:35 UTC
This (hopefully) isn't a bug report but just a usage question:

I want to run xpdf in a sandbox.  Problem is that a simple

  $ fireail xpdf /some/path/pdffile

Does not work because the path is not whitelisted.  Whitelisting the whole system seems wrong; xpdf should simply have read access to the file on the command line and nothing else (except config files of course).  However, it's not so easy to figure out at which position xpdf's files arguemnt is.  It's not necessarily the last one.

**Comment by rusty-snake** [comment] 2021-02-11 19:40
Duplicate of #838

**Comment by rusty-snake** [comment] 2021-02-11 19:40
> Does not work because the path is not whitelisted.

xpdf has a blacklisting profile, did you add the whitelisting stuff?

**Comment by domivogt** [comment] 2021-02-11 20:00
I've not changed anything.  This is the problem I want to solve:

```
$ firejail --profile=/usr/local/etc/firejail/xpdf.profile xpdf /data/foo.pdf
error: "/data/foo.pdf" file not found
```

It works if the file is in $HOME.

**Comment by rusty-snake** [comment] 2021-02-11 20:04
> I've not changed anything.

No globals.local or other *.local and nothing in firejail.config. Ok, does it work with `firejail --noprofile /usr/bin/xpdf /data/foo.pdf`.
Also is /data mounted with something "crazy" like fuse, nfs, ...?

**Comment by domivogt** [comment] 2021-02-11 20:28
> No globals.local or other *.local and nothing in firejail.config.

Firejail-0.9.64.4 is just installed as built, without any changes to anything (except seamonkey.local and iceweasel.local).

> Ok, does it work with firejail --noprofile /usr/bin/xpdf /data/foo.pdf.

Yes.  However, it looks weird overall:  If the file is in /data/.../foo.pdf, it works.  If it's in /home/data/.../foo.pdf it doesn't.  (/home is on a different partition, but not mounted with any exciting options:

```
/dev/sda1 on / type ext4 (rw,noatime,nodiratime,discard)
/dev/sda3 on /home type ext4 (rw,noatime,nodiratime,discard)
```

Is /home treated differently than other dirs?

> Also is /data mounted with something "crazy" like fuse, nfs, ...?

/data is just a world readable directory in the root filesystem.

> or symlinked from somewhere?

Nope.

> Shows firejail --debug xpdf /data/foo.pdf anything like "Disable /data"?

No.

**Comment by rusty-snake** [comment] 2021-02-11 20:30
> Is /home treated differently than other dirs?

Yes, only `/home/user` is present without `--allusers`.

**Comment by domivogt** [comment] 2021-02-11 20:39
Fair enough.  So, assuming you have the full path of a file, like /data/som/subdir/file.pdf.  Is there a simple way to whitelist that path, and only that path, regardless of any other active rules?

(And if that's possible, is it possible to remove write permissions on the path and to the file?)

**Comment by rusty-snake** [comment] 2021-02-11 20:50
> (And if that's possible, is it possible to remove write permissions on the path and to the file?)

`read-only /path/to/file`, if you only view pdfs, you could `read-only /data` and `read-only ${HOME}`.

>  Is there a simple way to whitelist that path, and only that path, regardless of any other active rules?

No, the are multiple options granting/denying access to a file.

Work `firejail --withelist=/data/foo.pdf xpdf /data/pdf`?

**Comment by rusty-snake** [comment] 2021-04-06 15:00
Looks like you need to comment the profile and the uncomment it line for line to find the cause.

**Comment by rusty-snake** [comment] 2021-05-12 18:18
I'm closing here due to inactivity, please fell free to request to reopen if you still have this issue.

**Closed by rusty-snake** 2021-05-12 18:18 UTC
