### ISSUE TITLE
Firejailed processes not always close properly

### ISSUE THREAD

**Issue by curiosity-seeker** [netblue30/firejail#725] opened 2016-08-17 13:35 UTC
I'm running Firejail 0.9.40 on Fedora 24. Sometimes I notice that for firejailed programmes which I close processes are still running. 

Example: Today I ran Thunderbird. firejail --tree shows:

```
9276:hank:/usr/bin/firejail /usr/bin/thunderbird 
  9277:hank:/usr/bin/firejail /usr/bin/thunderbird 
    9732:hank:gpg-agent --homedir /home/hank/.gnupg --use-standard-socket --daemon
```

Then I close Thunderbird and start it again after a while. Now firejail --tree shows:

```
9276:hank:/usr/bin/firejail /usr/bin/thunderbird 
  9277:hank:/usr/bin/firejail /usr/bin/thunderbird 
    9732:hank:gpg-agent --homedir /home/hank/.gnupg --use-standard-socket --daemon 
10897:hank:/usr/bin/firejail /usr/bin/thunderbird 
  10898:hank:/usr/bin/firejail /usr/bin/thunderbird 
    10900:hank:/usr/lib64/thunderbird/thunderbird
```

This is also confirmed, e.g., in ksysguard.

I had noticed something similar if I open a PDF file in Thunderbird with Okular. After closing Okular the respective processes are still shown in firejail -tree. 

I'm sorry for not being more specific as this observation is not always reproducible. My impression is that this only occurs with Thunderbird and Okular.

**Comment by netblue30** [comment] 2016-08-18 13:35
Can you do a test on the latest git version?

**Comment by curiosity-seeker** [comment] 2016-08-18 14:02
Sure! I just installed the copr build. I will test it and report!

**Comment by curiosity-seeker** [comment] 2016-08-18 17:51
With the copr version (0.9.42-1.201608171910git20e643e.fc24) the problem still exists. After closing Thunderbird, waiting a couple of minutes and starting it again, firejail --tree shows:
```
3841:hank:/usr/bin/firejail /usr/bin/thunderbird 
  3842:hank:/usr/bin/firejail /usr/bin/thunderbird 
    4310:hank:gpg-agent --homedir /home/hank/.gnupg --use-standard-socket --daemon 
8117:hank:/usr/bin/firejail /usr/bin/thunderbird 
  8118:hank:/usr/bin/firejail /usr/bin/thunderbird 
    8120:hank:/usr/lib64/thunderbird/thunderbird
```

**Comment by netblue30** [comment] 2016-08-18 21:32
What version of Thunderbird do you have? Here on Debian stable it seems to close down nicely.

**Comment by curiosity-seeker** [comment] 2016-08-19 18:10
I'm using v. 45.2.0

**Comment by netblue30** [comment] 2016-08-20 12:34
I'll have to look into it, thanks.

**Comment by curiosity-seeker** [comment] 2016-08-20 13:55
Thanks! If it happens - and it doesn't every time as mentioned earlier - and I close Thunderbird again, the latest processes (in above example PID 8117,8118,8210) are terminated properly. What's still running are the PIDs 3841 and 3842.

**Comment by SYN-cook** [comment] 2017-03-06 13:24
I can confirm this on Debian Stretch KDE. Also for me this only happens with Thunderbird and Okular. 

In the moment I don't have the KDE machine at hand, so I installed Okular on Debian Jessie Mate, and it's the same there.

When I start Okular with `firejail --trace okular` and close the window, the application keeps running until I press Ctrl+C:
```
...
2:okular:fopen /etc/rpc:0x14e8ca0
^C
Parent received signal 2, shutting down the child process...

Parent is shutting down, bye...

Child received signal 15, shutting down the sandbox...
klauncher: Exiting on signal 15
```

If the first instance is not terminated, I can launch a second, and the output of `firejail --tree` then looks like:
```
4502:user:firejail okular 
  4503:user:firejail okular 
    4510:user:kdeinit4: kdeinit4 Runnin e 
      4511:user:kdeinit4: klauncher [kdei e 
    4513:user:kdeinit4: kded4 [kdeinit]   
4534:user:firejail okular 
  4535:user:firejail okular 
    4537:user:okular 
```

**Comment by rekixex** [comment] 2017-07-12 22:07
I can confirm this on Ubuntu 16.04 with the latest Firejail version from git repository. In my experience, only **Okular** is affected so far.

@curiosity-seeker 

> After closing Okular the respective processes are still shown in firejail -tree.

Same here.

@SYN-cook 

> If the first "hanging" instance is not terminated, I can launch a normal behaving second one, and the output of `firejail --tree` then looks like
> 
> ```
> 4502:user:firejail okular 
>   4503:user:firejail okular 
>     4510:user:kdeinit4: kdeinit4 Runnin e 
>       4511:user:kdeinit4: klauncher [kdei e 
>     4513:user:kdeinit4: kded4 [kdeinit]   
> 4534:user:firejail okular 
>   4535:user:firejail okular 
>     4537:user:okular 
> ```

Same here. The second instance terminates properly after closing, but the first is still running.

Interestingly, when I open and close Okular normally and subsequently open Okular with firejail and close it, the instance terminates properly.

**Comment by rekixex** [comment] 2017-07-12 22:09
@netblue30 

I can confirm this on Ubuntu 16.04 with the latest Firejail version from git repository. In my experience, only **Okular** is affected so far.

@curiosity-seeker 

> After closing Okular the respective processes are still shown in firejail -tree.

Same here.

@SYN-cook 

> If the first "hanging" instance is not terminated, I can launch a normal behaving second one, and the output of `firejail --tree` then looks like
> 
> ```
> 4502:user:firejail okular 
>   4503:user:firejail okular 
>     4510:user:kdeinit4: kdeinit4 Runnin e 
>       4511:user:kdeinit4: klauncher [kdei e 
>     4513:user:kdeinit4: kded4 [kdeinit]   
> 4534:user:firejail okular 
>   4535:user:firejail okular 
>     4537:user:okular 
> ```

Same here. The second instance terminates properly after closing, but the first is still running.

Interestingly, when I open and close Okular normally and subsequently open Okular with firejail and close it, the instance terminates properly.

**Comment by curiosity-seeker** [comment] 2017-07-17 14:48
@rekixex : It doesn't happen anymore for me with Okular. Note that I'm using v. 1.0.3 with KDE Frameworks 5.36.0 and Qt 5.7.1 on Fedora 26. And I haven't observed this problem for Thunderbird anymore, either (v. 52.2.1).

However, I'm using a modified profile for both applications. For Thunderbird:
```
noblacklist ~/.gnupg
mkdir ~/.gnupg
whitelist ~/.gnupg

noblacklist ~/.thunderbird
mkdir ~/.thunderbird
whitelist ~/.thunderbird

noblacklist ~/.cache/thunderbird
mkdir ~/.cache/thunderbird
whitelist ~/.cache/thunderbird

whitelist ~/.config/mimeapps.list
read-only ~/.config/mimeapps.list
whitelist ~/.local/share/applications
read-only ~/.local/share/applications

whitelist ${HOME}/Downloads
whitelist ${HOME}/Uploads

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

include /etc/firejail/whitelist-common.inc

caps.drop all
netfilter
nonewprivs
noroot
protocol unix,inet,inet6,netlink
seccomp
tracelog

private-dev

noexec ${HOME}
noexec /tmp
```
And for Okular:
```
ignore private-tmp
include /etc/firejail/okular.profile

noexec ${HOME}
noexec /tmp
noexec /media
```
Btw., in Thunderbird I selected xdg-open as the default helper application for all file types.

**Comment by rekixex** [comment] 2017-07-17 19:32
@curiosity-seeker 

I tried what you did, but still doesn't work.

> And for Okular:
> 
> ```
> ignore private-tmp
> include /etc/firejail/okular.profile
> 
> noexec ${HOME}
> noexec /tmp
> noexec /media
> ```

This gives me `Error: cannot access profile file`. I commented out the line `include /etc/firejail/okular.profile` and now it starts Okular, but the problems are still there:

1) after closing Okular the respective processes are still running

2) Okular won't start the second instance (described in #1391)

**Comment by rekixex** [comment] 2017-07-17 19:34
@curiosity-seeker 

I tried what you did, but it doesn't work.

> And for Okular:
> 
> ```
> ignore private-tmp
> include /etc/firejail/okular.profile
> 
> noexec ${HOME}
> noexec /tmp
> noexec /media
> ```

This gives me `Error: cannot access profile file`. I commented out the line `include /etc/firejail/okular.profile` and now it starts Okular, but the problems are still there:

1) after closing Okular the respective processes are still running

2) Okular won't start the second instance (described in #1391)

**Comment by rekixex** [comment] 2017-07-18 02:16
@curiosity-seeker 

I tried what you did, but it doesn't work.

> And for Okular:
> 
> ```
> ignore private-tmp
> include /etc/firejail/okular.profile
> 
> noexec ${HOME}
> noexec /tmp
> noexec /media
> ```

This gives me `Error: cannot access profile file`. After I commented out the line `include /etc/firejail/okular.profile`, Okular opens, but problems are still there:

1) after closing Okular the respective processes are still running

2) Okular won't start the second instance (described in #1391)

**Comment by curiosity-seeker** [comment] 2017-07-19 11:39
@rekixex : I think it's not surprising that you cannot access `/etc/firejail/okular.profile`. You're using the Firejail git version which installs by default to `/usr/local`. Whereas I install it using

`./configure --prefix=/usr`

Hence, the path to your profiles is different (I believe it is `/usr/local/etc/firejail/okular.profile`).

Anyways, can you show us what `firejail --tree` reports when you start Okular and when you close it?

**Comment by rekixex** [comment] 2017-07-19 17:59
@curiosity-seeker You are right, I was in a hurry and forgot to change `/etc/firejail/okular.profile` to `/usr/local/etc/firejail/okular.profile`.

Here is what `firejail --tree` reports when I start Okular:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5370:user:okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

...and when I close it:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

**Comment by rekixex** [comment] 2017-07-19 18:02
@curiosity-seeker You are right, I was in a hurry and I missed to change `/etc/firejail/okular.profile` to `/usr/local/etc/firejail/okular.profile`.

Here is what `firejail --tree` reports when I start Okular:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5370:user:okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

...and when I close it:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

**Comment by rekixex** [comment] 2017-07-19 18:08
@curiosity-seeker You are right, I was in a hurry and I missed to change `/etc/firejail/okular.profile` to `/usr/local/etc/firejail/okular.profile`.

Here is what `firejail --tree` reports when I open Okular:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5370:user:okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

...and when I close it:

```
5366:user:firejail okular 
  5367:user:firejail okular 
    5375:user:kdeinit4: kdeinit4 Running...
      5376:user:kdeinit4: klauncher [kdeinit] --fd=8
    5378:user:kdeinit4: kded4 [kdeinit]
```

**Comment by smitsohu** [comment] 2017-10-11 22:01
Specifically regarding Okular: It should help launching kdeinit4 once normally, outside a sandbox. This could be done for example during session startup.

**Comment by smitsohu** [comment] 2017-10-12 00:08
Specifically regarding Okular: It should help to launch kdeinit4 inside a Firejail sandbox, and keep this instance running in the background. This could be done for example during session startup.

**Comment by chiraag-nataraj** [comment] 2019-05-21 23:16
I don't really think we have a proper solution for this besides working around things on an app-specific level. I'll close this for now since it feels like we should be targeting known offenders, as it were, in separate issues (if people are running into them). Feel free to re-open if you feel that we _should_ attempt to solve this more generally.

**Closed by chiraag-nataraj** 2019-05-21 23:16 UTC
Labels: bug
