### ISSUE TITLE
Use /usr/etc/login.defs after checking for /etc/login.defs

### ISSUE THREAD

**Issue by libreunkraut** [netblue30/firejail#3388] opened 2020-04-28 16:46 UTC
**Describe the bug**
firejail report an error on every run if no /etc/login.defs is found even though login.defs exists in /usr/etc/ where distro defaults are stored.

**To Reproduce**
Run firejail on any distribution without login.defs in /etc and instead being in /usr/etc

**Expected behavior**
firejail should use the login.defs available in /usr/etc

**Desktop:**
 - openSUSE Tumbleweed - 20200425
 - firejail version 0.9.62

**Comment by rusty-snake** [comment] 2020-04-28 16:51
Duplicate of #3145

**Closed by rusty-snake** 2020-04-28 16:51 UTC

**Comment by rusty-snake** [comment] 2020-04-28 16:52
It was fixed on master in https://github.com/netblue30/firejail/commit/cd184e9919bb67fb88ee6208c395682f5f0ba764.

**Comment by jubalh** [comment] 2020-04-29 11:24
And https://github.com/netblue30/firejail/commit/609be4fda2dda5557de864eba814c42fe2f40dca if I am not mistaken
