### ISSUE TITLE
No video playback with VLC

### ISSUE THREAD

**Issue by MrFrank17** [netblue30/firejail#3938] opened 2021-01-31 15:17 UTC
Hi,

VLC is no showing videos with the standard profile (using Kubuntu 20.10).
If I start it with `firejail --noprofile vlc` everything is fine as expected.

Starting vlc normally,  `journalctl --boot --pager-end --follow` gives me that:

audit[615706]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined pid=615706 comm="vlc" exe="/usr/local/bin/vlc" sig=31 arch=c000003e syscall=312 compat=0 ip=0x7f476f3c667d code=0x0
Jan 31 16:13:50 frank-laptop kernel: audit: type=1326 audit(1612106030.242:57): auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined pid=615706 comm="vlc" exe="/usr/local/bin/vlc" sig=31 arch=c000003e syscall=312 compat=0 ip=0x7f476f3c667d code=0x0
Jan 31 16:13:55 frank-laptop firejail[620322]: blacklist violation - sandbox 1853, exe kioslave5, syscall open64, path /proc/sys/kernel/core_pattern
Jan 31 16:13:55 frank-laptop firejail[620324]: blacklist violation - sandbox 1853, exe kioslave5, syscall open64, path /proc/sys/kernel/core_pattern

Any ideas?

Thanks
Frank

**Comment by rusty-snake** [comment] 2021-01-31 16:36
Duplicate of #3219, replace `seccomp` with `seccomp !kcmp` in vlc.profile.

**Comment by MrFrank17** [comment] 2021-01-31 17:06
Thanks, playback works now!
Something minor: it seems access to some KDE configuration files is still blocked (eg I am using a dark theme and without firejail vlc adapts to that style. Now it is shown in light colors. Also the filebrowser dialog has not all of my individual settings).The journal log shows nothing meaningful ...

**Comment by rusty-snake** [comment] 2021-01-31 17:17
vlc is a whitelisting profile, if you want to play files stored somewhere else then Desktop/Downloads/Music/Pictures/Videos you must add a `whitelist ${HOME}/path/to/file_or_dir` to `whitelist-player-common.local`. Files which store settings like for your Qt-theme should be `whitelist`ed (and maybe `read-only`ed) in `whitelist-common.inc`, looks like there are some paths missing. Do you know where KDE stores this?

**Comment by MrFrank17** [comment] 2021-01-31 19:50
I used `vlc.local`, but good to know that there are other ways as well.
Sorry, no idea how KDE handles that (or which folders are used).
I hoped to see a blacklist (or in this case a whitelist?) violation in the journal output.

**Comment by rusty-snake** [comment] 2021-02-01 06:57
> blacklist (or in this case a whitelist?) violation in the journal output.

Will not happen for missing `whitelist`. However, you can `firejail --build=~/vlc.profile vlc` and then compare all the `whitelist ${HOME}/...`.

**Comment by MrFrank17** [comment] 2021-02-01 21:50
Oh, wasn't aware about that possibility!
Was still a lot to look up - I added this in vlc.local.
Note these are the additional ones, have not checked if they all really needed. Maybe you can give me a hint ... 

include /etc/firejail/whitelist-common.inc
include whitelist-usr-share-common.inc

whitelist ${HOME}/.local/share/RecentDocuments
whitelist ${HOME}/.local/share/kioslave5/icons/hicolor
whitelist ${HOME}/.cache/thumbnails
whitelist ${HOME}/.config/pulse
whitelist ${HOME}/.pulse-cookie
whitelist ${HOME}/.cache/thumbnails
whitelist ${HOME}/.Xdefaults-frank-laptop
whitelist ${HOME}/.cache/mesa_shader_cache
whitelist /usr/share/kioslave5
whitelist /usr/share/texmf
whitelist /usr/share/vlc
whitelist /usr/share/kubuntu-default-settings


To have it fully functional I commented also out all the disable*.inc in vlc.profile. That's for sure too much, but I did not had the time to look into that.

**Comment by rusty-snake** [comment] 2021-02-02 11:33
`${HOME}/.local/share/RecentDocuments`, `${HOME}/.cache/thumbnails`: what the name says
`${HOME}/.config/pulse`, `${HOME}/.pulse-cookie`: pulse audio
`${HOME}/.cache/mesa_shader_cache`: just a cache
`/usr/share`: system-wide, not relevant for theme change by user

**Comment by MrFrank17** [comment] 2021-02-02 21:05
Ok, I works now!
The solution is surprisingly simple after all I have tried out - I added to my local profile:
`noblacklist ${DOCUMENTS}`
`noblacklist ${PICTURES}`
Not sure why this enough, but well, it works ...

**Closed** 2021-02-03 18:12 UTC
