### ISSUE TITLE
Unable to firejail tutanota desktop client appimage 

### ISSUE THREAD

**Issue by Neo00001** [netblue30/firejail#2831] opened 2019-07-05 14:47 UTC
I'm getting this error message:
`Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/globals.local
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 15587, child pid 15590

**     Warning: dropping all Linux capabilities     **
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 73.37 ms
/bin/bash: /run/firejail/appimage/.appimage-15587/AppRun: Permission denied

Parent is shutting down, bye...
AppImage unmounted`

Specs- Os:Manjaro Kernel:5.1.15  firejail version:0.9.60

**Comment by rusty-snake** [comment] 2019-07-05 14:57
Duplicate of #2690?

**Comment by crass** [comment] 2019-07-08 23:58
Yep duplicate. Until this is fixed, probably the best way to get it to work is to repack the appimage settings execute perms on all directories and read perms on all files for everyone.

**Closed by crass** 2019-07-08 23:58 UTC
Labels: duplicate
