### ISSUE TITLE
firejail appimage. But Black Screen Reboot.

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#3084] opened 2019-12-16 12:17 UTC
https://www.balena.io/etcher

Download Appimage.
And...

> firejail --appimage --private --x11 balenaEtcher-1.5.69-x64.appimage

Black Screen. :(
I am System Reboot.
My Os is Debian 10 XFCE.

Help me.

**Comment by rusty-snake** [comment] 2019-12-16 13:19
`--appimage` should be the last argument.
`firejail --private --x11 --appimage balenaEtcher-1.5.69-x64.appimage`

If you execute this command your system reboots?

**Comment by smitsohu** [comment] 2019-12-16 14:15
Your session is killed only if there is an `x11` option, right?

That would be a duplicate of #2205. In this case you need to 
* add one of the `net` options to your command and 
* deny access to /tmp/.ICE-unix and/or ~/.ICEauthority, either by blacklisting them or with one of the `private*` options. Further it might be necessary to set `restricted-network` to `no` in /etc/firejail/firejail.config

**Closed** 2020-01-05 23:05 UTC
