### ISSUE TITLE
Invalid --env setting, Failed to compile git version on Arch Linux with `--enable-apparmor`

### ISSUE THREAD

**Issue by oogeek** [netblue30/firejail#4212] opened 2021-04-25 06:53 UTC
**Environment**
I am using:
```
Arch Linux 5.11.16-arch1-1
```
gcc 10.2.0
```
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib--enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
``` 
I have checked that it has the newest commits.

**Additional context**
I have tried two ways to compile it. One is to install it with `yay -S firejail-git`, another is to `git clone` and manually run `configure` and `make`

**Checklist**
 - [ ] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
 - [ ] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
 - [x] I have performed a short search for similar issues (to avoid opening a duplicate).
 - [ ] If it is a AppImage, `--profile=PROFILENAME` is used to set the right profile.
 - [ ] Used `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 PROGRAM` to get english error-messages.
 - [ ] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
 - [ ] This is not a question. Questions should be asked in https://github.com/netblue30/firejail/discussions.

**Comment by rusty-snake** [comment] 2021-04-25 06:59
Do you get any error?

**Comment by oogeek** [comment] 2021-04-25 07:00
```
gcc -march=x86-64 -mtune=generic -O1 -pipe -fno-plt -ggdb  -O2 -DVERSION='"0.9.65"'  -DPREFIX='"/usr"' -DSYSCONFDIR='"/etc/firejail"' -DLIBDIR='"/usr/lib"' -DBINDIR='"/usr/bin"'  -DHAVE_OUTPUT -DHAVE_X11 -DHAVE_PRIVATE_HOME -DHAVE_APPARMOR  -DHAVE_USERTMPFS -DHAVE_DBUSPROXY -DHAVE_FIRETUNNEL -DHAVE_GLOBALCFG -DHAVE_CHROOT -DHAVE_NETWORK -DHAVE_USERNS -DHAVE_FILE_TRANSFER -DHAVE_WHITELIST   -fstack-protector-all -D_FORTIFY_SOURCE=2 -fPIE -Wformat -Wformat-security   -c main.c -o main.o
/usr/bin/ld: apparmor.o: in function `apparmor_test':
/home/szz/.cache/yay/firejail-git/src/firejail-git/src/jailtest/apparmor.c:28: undefined reference to `aa_gettaskcon'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: jailtest] Error 1
make[1]: Leaving directory '/home/szz/.cache/yay/firejail-git/src/firejail-git/src/jailtest'
make: *** [Makefile:42: src/jailtest/jailtest] Error 2
make: *** Waiting for unfinished jobs....
/usr/bin/ld: apparmor.o: in function `print_apparmor':
/home/szz/.cache/yay/firejail-git/src/firejail-git/src/firemon/apparmor.c:28: undefined reference to `aa_gettaskcon'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: firemon] Error 1
make[1]: Leaving directory '/home/szz/.cache/yay/firejail-git/src/firejail-git/src/firemon'
make: *** [Makefile:42: src/firemon/firemon] Error 2
/usr/bin/ld: join.o: in function `extract_apparmor':
/home/szz/.cache/yay/firejail-git/src/firejail-git/src/firejail/join.c:65: undefined reference to `aa_is_enabled'
/usr/bin/ld: sandbox.o: in function `set_apparmor':
/home/szz/.cache/yay/firejail-git/src/firejail-git/src/firejail/sandbox.c:133: undefined reference to `aa_change_onexec'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: firejail] Error 1
make[1]: Leaving directory '/home/szz/.cache/yay/firejail-git/src/firejail-git/src/firejail'
make: *** [Makefile:42: src/firejail/firejail] Error 2
gcc  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -pie -fPIE -Wl,-z,relro -Wl,-z,now -lpthread -o ftee main.o
make[1]: Leaving directory '/home/szz/.cache/yay/firejail-git/src/firejail-git/src/ftee'
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by oogeek** [comment] 2021-04-25 07:02
This is by first
`./configure --prefix=/usr --enable-apparmor`
'make'
```
gcc  -pie -fPIE -Wl,-z,relro -Wl,-z,now -lpthread -o firejail appimage.o appimage_size.o arp.o bandwidth.o caps.ocgroup.o checkcfg.o chroot.o cmdline.o cpu.o dbus.o dhcp.o env.o fs.o fs_bin.o fs_dev.o fs_etc.o fs_home.o fs_hostname.o fs_lib.o fs_lib2.o fs_logger.o fs_mkdir.o fs_trace.o fs_var.o fs_whitelist.o join.o ls.o macros.o main.o mountinfo.o netfilter.o netns.o network.o network_main.o no_sandbox.o output.o paths.o preproc.o profile.o protocol.o pulseaudio.o restrict_users.o restricted_shell.o rlimit.o run_files.o run_symlink.o sandbox.o sbox.o seccomp.o selinux.o shutdown.o usage.o util.o x11.o ../lib/common.o ../lib/ldd_utils.o ../lib/firejail_user.o ../lib/errno.o../lib/syscall.o
/usr/bin/ld: join.o: in function `extract_apparmor':
/home/szz/firejail/src/firejail/join.c:65: undefined reference to `aa_is_enabled'
/usr/bin/ld: sandbox.o: in function `set_apparmor':
/home/szz/firejail/src/firejail/sandbox.c:133: undefined reference to `aa_change_onexec'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:10: firejail] Error 1
make[1]: Leaving directory '/home/szz/firejail/src/firejail'
make: *** [Makefile:42: src/firejail/firejail] Error 2
```

**Comment by oogeek** [comment] 2021-04-25 07:04
The weird thing to note that I did succeed once and once only. I just don't know why.

**Comment by rusty-snake** [comment] 2021-04-25 07:09
FWIW: https://aur.archlinux.org/packages/firejail-git/#comment-748310

**Comment by oogeek** [comment] 2021-04-25 07:12
> FWIW: https://aur.archlinux.org/packages/firejail-git/#comment-748310

I have seen it but I think I have keep my Arch up to date. I just do another update check and it shows that everything is in sync.

**Comment by glitsj16** [comment] 2021-04-26 09:48
@oogeek I'm on Arch Linux too and as collaborator here I build from git master several times per day. I have a custom PKGBUILD, but I've tested firejail-git from AUR also. That builds just fine for me, and it includes the --enable-apparmor switch you mention. So alas I cannot reproduce.

Have you tried [building in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) yet? That's the best way to determine what's going on at your end, especially if you're not 100% sure your system is fully updated or something else in your setup causes this.

> The reason why I tried to use git version is that I got error like
Error: invalid --env setting
Process number1 failed to sync with peer number2 ...
when using the firejail 0.9.64.4-1 from Arch Repo.

Can you show us the full command and output from env when you get this error? I think that's the problem you should focus on first.

**Comment by oogeek** [comment] 2021-04-26 10:49
@glitsj16 Thanks for your suggestion. I tried to build it in chroot and it works. Now I need to dig into the env and see what is wrong.

**Comment by glitsj16** [comment] 2021-04-26 11:02
@oogeek Well that's progress at least. Perhaps https://github.com/netblue30/firejail/issues/3678 and the other issues discussed in there can offer some context.

**Comment by oogeek** [comment] 2021-04-26 11:52
```
Autoselecting /bin/bash as shell
Building quoted command line: 'dig'
Command name #dig#
Found dig.profile profile in /etc/firejail directory
Found dig.local profile in /etc/firejail directory
Found globals.local profile in /etc/firejail directory
Found disable-common.inc profile in /etc/firejail directory
Found disable-exec.inc profile in /etc/firejail directory
Found disable-passwdmgr.inc profile in /etc/firejail directory
Found disable-programs.inc profile in /etc/firejail dire
ctory
Found disable-xdg.inc profile in /etc/firejail directory
Found whitelist-common.inc profile in /etc/firejail directory
Found whitelist-usr-share-common.inc profile in /etc/firejail directory
Found whitelist-var-common.inc profile in /etc/firejail directory
DISPLAY=:0 parsed as 0
Enabling IPC namespace
Using the local network stack
Initializing child process
Host network configured
PID namespace installed
Mounting tmpfs on /run/firejail/mnt directory
Creating empty /run/firejail/mnt/seccomp directory
Creating empty /run/firejail/mnt/seccomp/seccomp.protocol file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec file
Creating empty /run/firejail/mnt/seccomp/seccomp.postexec32 file
IBUS_ADDRESS=unix:path=/run/user/1000/bus,fcitx_random_string=e2668907616b424db513e147e1b0623f
IBUS_DAEMON_PID=1356
IBUS_ADDRESS=
Error: invalid --env setting
Error: proc 10711 cannot sync with peer: unexpected EOF
Peer 10712 unexpectedly exited with status 1
```

**Comment by oogeek** [comment] 2021-04-26 11:53
And this is 
`printenv`
```
MAIL=/var/spool/mail/szz
LANGUAGE=en_US.UTF-8
USER=szz
XDG_SEAT=seat0
XDG_SESSION_TYPE=tty
SHLVL=2
MOTD_SHOWN=pam
HOME=/home/szz
HG=/usr/bin/hg
GTK_MODULES=canberra-gtk-module
SYSTEMD_EXEC_PID=616
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GTK_IM_MODULE=fcitx
LOGNAME=szz
JOURNAL_STREAM=8:21479
_=/usr/bin/printenv
XDG_SESSION_CLASS=user
TERM=xterm-kitty
XDG_SESSION_ID=1
WINDOWPATH=1
PATH=/home/szz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
INVOCATION_ID=2082d0982bb747dfb7f50e1ee18d107f
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
LANG=en_US.UTF-8
XMODIFIERS=@im=fcitx
XAUTHORITY=/home/szz/.Xauthority
SHELL=/bin/bash
QT_IM_MODULE=fcitx
XDG_VTNR=1
PWD=/home/szz
KITTY_WINDOW_ID=1
WINDOWID=41943054
COLORTERM=truecolor
TERMINFO=/usr/lib/kitty/terminfo
OLDPWD=/home/szz
P9K_TTY=old
EDITOR=vim
VISUAL=vim
RANGER_LOAD_DEFAULT_RC=FALSE
MANPAGER=/bin/sh -c "col -b | vim --not-a-term -c 'set ft=man ts=8 nomod nolist noma' -"
P9K_SSH=0
```

**Comment by rusty-snake** [comment] 2021-04-26 11:56
Duplicate of #3965

**Comment by oogeek** [comment] 2021-04-26 11:58
> Duplicate of #3965

Thanks for mentioning the cause. 😄  Sorry for any inconvenience. Shall I close the issue?

**Closed** 2021-05-02 04:15 UTC

**Comment by oogeek** [comment] 2021-05-23 05:43
So after reducing the packages on my Arch setup from 1500+ to 900+, the error disappears. It is really strange.
