### ISSUE TITLE
mpv 0.36.0 + pipewire 0.3.75 dbus error

### ISSUE THREAD

**Issue by jaredmo** [netblue30/firejail#5921] opened 2023-07-25 13:46 UTC
### Description

Attempting to open a file with mpv 0.36.0 results in the following error. I am running an up-to-date Arch Linux system with firejail 0.9.72.

```
dbus[60]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file dbus-message.c line 1373.
This is normally a bug in some application using the D-Bus library.
```

### Steps to Reproduce

Open any media file with mpv.

### Expected behavior

File opens and plays successfully.

### Actual behavior

Presented with dbus error message.

### Behavior without a profile

File opens and plays successfully.

### Additional context

None.

### Environment

- Arch Linux
- firejail version 0.9.72

### Checklist

- [x] The issues is caused by firejail (i.e. running the program by path (e.g. `/usr/bin/vlc`) "fixes" it).
- [x] I can reproduce the issue without custom modifications (e.g. globals.local).
- [x] The program has a profile. (If not, request one in `https://github.com/netblue30/firejail/issues/1139`)
- [x] The profile (and redirect profile if exists) hasn't already been fixed [upstream](https://github.com/netblue30/firejail/tree/master/etc).
- [x] I have performed a short search for similar issues (to avoid opening a duplicate).
  - [x] I'm aware of `browser-allow-drm yes`/`browser-disable-u2f no` in `firejail.config` to allow DRM/U2F in browsers.
- [x] I used `--profile=PROFILENAME` to set the right profile. (Only relevant for AppImages)

### Log

<details>
<summary>Output of <code>LC_ALL=C firejail /path/to/program</code></summary>
<p>

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
```

</p>
</details>

<details>
<summary>Output of <code>LC_ALL=C firejail --debug /path/to/program</code></summary>
<p>

https://gist.github.com/jaredmo/ca032153257acca1242f355572b5e5f6

</p>
</details>

**Comment by kmk3** [comment] 2023-07-25 18:08
Quoting a relevant comment from #5917:

@kmk3 [on Jul 25](https://github.com/netblue30/firejail/pull/5917#issuecomment-1649839174):

> @polyzen [on Jul 24](https://github.com/netblue30/firejail/pull/5917#discussion_r1272800884):
> 
> > Without it:
> > 
> > ```
> > dbus[60]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file dbus-message.c line 1373.
> > This is normally a bug in some application using the D-Bus library.
> > 
> >   D-Bus not built with -rdynamic so unable to print a backtrace
> > ```
> 
> I have the exact same issue on Artix, but I think it might be a regression in
> pipewire 0.3.75 rather than in mpv, since it happens with `mpv --ao=pipewire`
> but not with `mpv --ao=alsa`.
> 
> @polyzen [on Jul 24](https://github.com/netblue30/firejail/pull/5917#issue-1819195045):
> 
> > Maybe could also use `dbus-system.talk org.freedesktop.DBus
> > org.freedesktop.RealtimeKit1`. Not really sure how this works.
> 
> I'm not sure either, but note that pipewire depends on that but not mpv:
> 
> ```
> $ pacman -Sii extra/mpv      | grep -e realtime -e rtkit
> $ pacman -Sii extra/pipewire | grep -e realtime -e rtkit
>                   realtime-privileges: realtime privileges with rt module
>                   rtkit: realtime privileges with rtkit module
> $ pacman -Q pipewire mpv
> pipewire 1:0.3.75-2
> mpv 1:0.36.0-1
> ```
> 
> And that mpv itself does not appear to use dbus at all:
> 
> ```
> $ cd mpv
> $ git checkout v0.36.0
> HEAD is now at f4210f8490 Release 0.36.0
> $ git grep -i dbus
> $
> ```
> 
> In any case, thanks for the workaround.

**Comment by kmk3** [comment] 2023-07-25 18:09
I have downgraded pipewire-related packages to 0.3.74 and restarted pipewire on
Artix and can confirm that mpv 0.36.0 works normally with it.

So it indeed seems that the underlying issue is with pipewire 0.3.75 rather
than with mpv.

**Comment by rusty-snake** [comment] 2023-07-25 18:12
@kmk3 has this anything todo with pipewire vor is it just that mpv is the only Programm that uses pipewire?

**Comment by kmk3** [comment] 2023-07-25 18:40
> @kmk3 has this anything todo with pipewire

As mentioned [here][1], the error happens with `--ao=pipewire` but not
`--ao=alsa`, so yes.

> is it just that mpv is the only Programm that uses pipewire?

mpv includes pipewire.h and can use pipewire directly as the backend (if built
with pipewire support); other programs may use it through the alsa/pulse/etc
connectors.

[1]: https://github.com/netblue30/firejail/issues/5921#issuecomment-1650305934

**Comment by rusty-snake** [comment] 2023-07-25 18:43
> > has this anything todo with pipewire

Oops. Meant  to do with mpv.

**Comment by kmk3** [comment] 2023-07-25 18:47
Strangely, it appears that the error only occurs with the exact combination of
the latest mpv + the latest pipewire:

Works:

* mpv 1:0.35.1-8.2 + alsa
* mpv 1:0.35.1-8.2 + pipewire 1:0.3.74-1
* mpv 1:0.35.1-8.2 + pipewire 1:0.3.75-2
* mpv 1:0.36.0-1   + alsa
* mpv 1:0.36.0-1   + pipewire 1:0.3.74-1

Fails:

* mpv 1:0.36.0-1   + pipewire 1:0.3.75-2

Can anyone else reproduce?

**Comment by polyzen** [comment] 2023-07-25 19:55
> Strangely, it appears that the error only occurs with the exact combination of the latest mpv + the latest pipewire:
> 
> Works:
> 
>     * mpv 1:0.35.1-8.2 + pipewire 1:0.3.74-1
> 
>     * mpv 1:0.35.1-8.2 + pipewire 1:0.3.75-2
> 
> Fails:
> 
>     * mpv 1:0.36.0-1   + pipewire 1:0.3.75-2
> 
> 
> Can anyone else reproduce?

Can confirm these.

**Comment by rusty-snake** [comment] 2023-07-26 16:56
https://github.com/mpv-player/mpv/issues/12022

**Comment by kmk3** [comment] 2023-07-26 20:47
> [mpv-player/mpv#12022](https://github.com/mpv-player/mpv/issues/12022)

> Should be fixed by
> https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/55812195ce3b77317e7a2dc642b78271f3a45c8e
> in the next pipewire release.

In the mean time, the following workaround (based on #5917) can be added to
~/.config/firejail/mpv.local:

```
dbus-system filter
ignore dbus-system none
```

Closing this since the bug was fixed upstream.

**Closed by kmk3** 2023-07-26 20:47 UTC
Labels: notourbug
