### ISSUE TITLE
"generic.profile" vs "default.profile" ambiguity

### ISSUE THREAD

**Issue by vn971** [netblue30/firejail#498] opened 2016-05-03 23:32 UTC
Please fix the ambiguity in either of the two directions.

Currently, firejail does ship a `generic.profile` file, and uses it when possible. On the other hand, `firejail-profile` manual says it will look for `default.profile` and `server.profile` files.

I find `default.profile` to be a better name, but `generic` is used already, so I guess I fully leave the choice to the author..

**Comment by netblue30** [comment] 2016-05-04 13:03
From man firejail-profile:
`````
      3. Use a default.profile file if the sandbox is started  by  a  regular
       user, or a server.profile file if the sandbox is started by root. Fire‐
       jail looks for these files in ~/.config/firejail directory, followed by
       /etc/firejail  directory [...]
`````

**Comment by vn971** [comment] 2016-05-04 14:51
Cool, thanks.:)

**Comment by netblue30** [comment] 2016-05-04 17:04
Fixed, give it a try and let me know if you find anything else. I'll update the project webpages after I release the next version. Thanks.

**Comment by vn971** [comment] 2016-05-15 10:04
Hm, I'm not sure it works. I'm testing the following scheme now:
* empty ~/.config/firejail directory
* the directory /etc/firejail contains only `firejail.config` and `default.profile`, with default.profile being generated by `echo syntaxError > /etc/firejail/default.profile`
* starting just the `firejail` without any additional command line arguments.

Expected: firejail failing to load itself because either the absence of a profile file, or because of incorrect syntaxt in it.

Observe: firejail actually loading itself. With empty rule set it seems.

**Comment by netblue30** [comment] 2016-05-17 11:18
This is what I get:
`````
$ ls /etc/firejail/
default.profile
$ firejail
Reading profile /etc/firejail/default.profile
Error: line 1 in /etc/firejail/default.profile is invalid
`````
I would say it is the expected behavior. Not a bug.

**Comment by vn971** [comment] 2016-05-17 11:37
Hm, that's strange.
It still does not work for me. I even removed both the `/etc/firejail` and `~/.config/firejail` directories, but firejail still loads itself.
Maybe I've hit some temporary bug? I'll re-compile from `master`.

**Comment by vn971** [comment] 2016-05-17 11:44
I re-compiled, but still observe the "bug". (If anything, I use ArchLinux now, with the following build "script" https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firejail-git )

**Comment by vn971** [comment] 2016-05-17 12:03
Output for `firejail --debug`  (first lines):

```
Command name #bash#
Attempting to find default.profile...
DISPLAY :0.0, 0
Using the local network stack
Parent pid 2477, child pid 2478
Initializing child process
Host network configured
PID namespace installed
```

**Comment by netblue30** [comment] 2016-05-31 15:17
I have the new release out, give it a try and I'll reopen the bug if you still have problems.

**Comment by vn971** [comment] 2016-07-14 16:26
Hi! Sorry for the late reply. The bug persists in recent versions of `firejail`, too. My directory structure and the observed bug are the same as described earlier:
https://github.com/netblue30/firejail/issues/498#issuecomment-219276532
`firejail --version` gives "firejail version 0.9.41".

**Comment by netblue30** [comment] 2016-07-14 16:54
OK, let's start from the beginning. On version 0.9.41, print here the commands you run and the output you get.

**Comment by vn971** [comment] 2016-07-14 17:23
* `mv ~/.config/firejail ~/.config/firejail2`
* delete all files in `/etc/firejail` except `/etc/firejail/firejail.config`
* stard `firejail` .Without any additional command line arguments.
* expected: failure, observed: firejail successfully started.

**Comment by vn971** [comment] 2016-07-14 17:35
Alternative one-liner to show the bug:
`firejail --noprofile --private --blacklist=/etc/firejail firejail`
In this example, inner firejail should not have access to any profiles, so it should fail. In fact it does not fail.

**Comment by vn971** [comment] 2016-07-14 17:39
* updated comment above ^

**Comment by vn971** [comment] 2016-07-14 17:53
@netblue30 Can you reproduce with the last (simple) example?

**Comment by netblue30** [comment] 2016-07-14 19:35
`````
$ firejail --noprofile --private --blacklist=/etc/firejail firejail
Parent pid 26416, child pid 26417

Child process initialized
Warning: an existing sandbox was detected. /bin/bash will run without any additional sandboxing features in a /bin/sh shell
$ 
`````
It doesn't get a chance to fail, but it doesn't start either. It detects an existing sandbox, and it runs a normal bash session (see the warning).

If you force it to start with --force, this is what happens:
`````
$ firejail --noprofile --private --blacklist=/etc/firejail firejail --force
Parent pid 26475, child pid 26476

Child process initialized
Warning: Firejail configuration file /etc/firejail/firejail.config not found

Parent is shutting down, bye...
$
`````
So it fails, as it should be.

**Comment by vn971** [comment] 2016-07-14 20:26
@netblue30  sorry, indeed it does not work without "firejail.config". I had to only blacklist `/etc/firejail/default.profile`.

This command still shows the bug:
`firejail --noprofile --private --blacklist=/etc/firejail/default.profile firejail --force`
Can you test it?..

**Comment by netblue30** [comment] 2016-07-14 22:39
`````
$ firejail --noprofile --private --blacklist=/etc/firejail/default.profile firejail --force
Parent pid 27707, child pid 27708

Child process initialized
Error: cannot open profile file /etc/firejail/default.profile

Parent is shutting down, bye...
`````

It doesn't find a default.profile and it is shutting down. Is this a bug? You can add --noprofile at the end of the command and it will start.

**Comment by vn971** [comment] 2016-07-15 09:26
@netblue30 sorry again, I forgot my computer does not have the file ("/etc/firejail/default.profile"), so my `--blacklist` did nothing.
To reproduce the bug on a fresh environment, the following is needed:
```
mv /etc/firejail/default.profile /etc/firejail/default2.profile
firejail --noprofile --private firejail --force
```
Or, alternatively, this:
```
mv ~/.cache/firejail ~/.cache/firejail2
mv /etc/firejail/default.profile /etc/firejail/default2.profile
firejail
```

**Comment by vn971** [comment] 2016-07-15 09:28
EDITED comment above ^

**Comment by netblue30** [comment] 2016-07-18 12:59
> If your patience has not been spent already yet...

No problem, keep going. It usually ends up with me fixing some hard to catch bug. This is what I do:
`````
$ sudo mv /etc/firejail/default.profile /etc/firejail/default2.profile
$ firejail --noprofile --private firejail
Parent pid 24561, child pid 24562

Child process initialized
$
`````
So far so good. Firejail doens't care /etcfirejail/default.profile is missing because it was told not to care by --noprofile. Then I run the second command:
`````
$ firejail --force
Parent pid 7, child pid 8

Child process initialized
$
`````
This one shouldn't succeed because the default profile is missing. You are right, it is a bug!

**Comment by vn971** [comment] 2016-07-18 14:45
Cool!

**Comment by netblue30** [comment] 2016-07-20 15:48
Fixed in git, thanks!

**Closed by netblue30** 2016-07-20 15:48 UTC
Labels: bug

**Comment by vn971** [comment] 2016-07-20 17:13
@netblue30 indeed it works now. Thanks!
