### ISSUE TITLE
Can you install applications within a firejail, kinda like chroot?

### ISSUE THREAD

**Issue by Raj2032** [netblue30/firejail#2477] opened 2019-02-25 23:39 UTC
Can you install applications within a firejail, kinda like chroot? If so how do I do this?

**Comment by smitsohu** [comment] 2019-02-26 18:21
Duplicate of #2360 ? Also note that there is indeed a `--chroot` option.

**Comment by Raj2032** [comment] 2019-02-26 23:14
I see.

**Comment by Raj2032** [comment] 2019-02-26 23:36
@smitsohu I need a bit of help trying to understand some of the commands.

`sudo debootstrap --arch=amd64 sid /chroot/sid` I understand `debootstrap` is trying to create a debian file system inside the folder but what does this mean `--arch=amd64 sid /chroot/sid`?

`sudo firejail --noprofile --chroot=/chroot/sid`

So I understand that you are trying to start a firejail chroot service and I understand that you are using a `--noprofile` as a profile as the default profile is too restrictive, but what does this mean `--chroot=/chroot/sid`?

**Comment by smitsohu** [comment] 2019-02-27 00:11
@Raj2032 for easy and quick results I would just try the overlay approach, as described in #2360. You can also have something persistent with the `--overlay-named` option.

`sudo debootstrap --arch=amd64 sid /chroot/sid`
What you are trying there is installing a new Debian inside /chroot/sid. sid is the name of the Debian release, amd64 is the instruction set of your cpu. I think what is still missing is a server from which the Debian image is downloaded.

> what does this mean `--chroot=/chroot/sid`

It means that Firejail chroots into this folder before running the application.

**Comment by Raj2032** [comment] 2019-02-28 07:23
`--overlay-named` Doesn't this mean that everything inside the sandbox deletes eventually?

Say if I downloaded lets just say Opera browser as a deb package, then how do I install that inside the firejail chroot?

**Closed** 2019-03-15 15:46 UTC
