### ISSUE TITLE
Garbled VLC menus?

### ISSUE THREAD

**Issue by mr-blobbyyy** [netblue30/firejail#1277] opened 2017-05-17 14:15 UTC
Latest firejail 0.9.46.
Antergos XFCE 4.12 latest updates with Mesa AMD drivers with option `TearFree`.
Latest VLC 2.2.4.

Hard to describe, but I've confirmed the appearance is fine under a non-jailed VLC instance.
Confirmed with hwa (in VLC) checked on/off, changing different style/icon themes in XFCE settings. The videos otherwise play normally, it's just the menus in VLC all look garbled.

**Comment by mr-blobbyyy** [comment] 2017-05-17 14:23
Uh oh, I just realized that hwa is not being utilized on my 4k videos as I'm noticing high cpu usage while the hwa option is on "automatic" or "vdpau" -- which normally is fine otherwise. Looks like the latest update is not letting VLC utilize hwa for me.

**Comment by SpotComms** [comment] 2017-05-17 16:07
I'm not able to reproduce your first issue, but I can try and help with your second.

Does hardware decoding work when not running inside Firejail? If not, its either due to the video format not being supported or VA-API/VDPAU not being configured correctly. AFAIK H.265 is the recommended encoding for 4K and its only supported under newer Intel processors. And VA-API/VDPAU configuration is a bit tricky in the first place, Chromium and VLC do seem to do their own auto-configuration assuming the required packages are at least installed though.

If it does work when running outside of Firejail can you try and comment out 'private-bin' and give that a test?

https://wiki.archlinux.org/index.php/Hardware_video_acceleration

**Comment by mr-blobbyyy** [comment] 2017-05-17 16:34
@SpotComms yeah you're right, I think mesa isn't the best at decoding 4k h264. Interesting to see how vlc only pegs 1 core (25%) of my cpu when both hwa is enabled/disabled. I tested out some other 1080p videos and these work as expected in firejail with hwa enabled and no modification.

And by "menus" I meant menu windows like the preferences window. It seems like individual items like combo boxes and selection items are garbled. Hovering over them also produces some strange behaviour. Most likely a mesa issue but odd that it doesn't occur in a non-jailed environment.

**Comment by mr-blobbyyy** [comment] 2017-05-17 17:00
> Garbled VLC menus

I found the offending vlc.profile option: `ipc-namespace` -- comment that out and my windows and menu preferences are back to normal again. Need confirmation.

**Comment by netblue30** [comment] 2017-05-18 14:00
All fixed in https://github.com/netblue30/firejail/pull/1279

**Closed by netblue30** 2017-05-18 14:00 UTC
Labels: bug
