### ISSUE TITLE
Can't open keepassxc attachments while using firejail

### ISSUE THREAD

**Issue by ghost** [netblue30/firejail#2311] opened 2018-12-22 21:36 UTC
Can't open attachments while using firejail version 0.9.56 or master branch on up to date stable Manjaro KDE and keepassxc with default firejail profile, i'm getting  this keepassxc error in console:

`Unable to detect a launcher for 'file:///tmp/tEMESW.New.rtf'` 

thanks

**Comment by rusty-snake** [comment] 2018-12-22 21:57
@Lockdis Hi.
Works `firejail --noprofile keepassxc`?
Works `firejail --ignore=private-tmp keepassxc`?

**Comment by Lockdis** [comment] 2018-12-23 01:33
it's working with `firejail --noprofile keepassxc?`
and not working with `firejail --ignore=private-tmp keepassxc`

**Comment by SkewedZeppelin** [comment] 2018-12-23 02:49
This is expected behaviour.
See https://github.com/netblue30/firejail/issues/1718#issuecomment-406819438

**Comment by Lockdis** [comment] 2018-12-23 12:58
but even if i disable firejail on Kate i can't launch it from firejailed keepass, is a security mesure?

**Comment by rusty-snake** [comment] 2018-12-28 22:31
@Lockdis well, note that it is dangerous.
```
$ firejail --ignore=private-bin --ignore=private-etc keepassxc
$ # OR permanent
$ echo -e "ignore private-etc\nignore private-bin" >> ~/.config/firejail/keepassxc.local
```

**Comment by rusty-snake** [comment] 2019-04-10 16:22
Closing here, because the account starting the topic was deleted and it's not a real bug.

**Closed by rusty-snake** 2019-04-10 16:22 UTC
Labels: information
