### ISSUE TITLE
skypeforlinux not starting with firejail 0.9.50 on ubuntu

### ISSUE THREAD

**Issue by badpenguin** [netblue30/firejail#1730] opened 2018-01-14 13:01 UTC
firejail 0.9.50 on ubuntu is fine with private-dev but i had to insert at the top:

```
noblacklist /var/run/systemd
read-only /var/run/systemd
```

otherwise it will not start

**Comment by Fred-Barclay** [comment] 2018-01-17 02:15
G'day @badpenguin 
Can you try with the newest firejail 0.9.52 release? Version 0.9.50 is the old release and won't be getting security or stability updates.
Cheers!
Fred

**Comment by Real-Gecko** [comment] 2018-01-22 08:31
Does not work for me either with 0.9.52, here's console output:
```
[realgecko@archlinux ~]$ firejail --version
firejail version 0.9.52

Compile time support:
        - AppArmor support is disabled
        - AppImage support is enabled
        - bind support is enabled
        - chroot support is enabled
        - file and directory whitelisting support is enabled
        - file transfer support is enabled
        - git install support is disabled
        - networking support is enabled
        - overlayfs support is enabled
        - private-home support is enabled
        - seccomp-bpf support is enabled
        - user namespace support is enabled
        - X11 sandboxing support is enabled

[realgecko@archlinux ~]$ which skypeforlinux
/usr/local/bin/skypeforlinux
[realgecko@archlinux ~]$ skypeforlinux
Reading profile /etc/firejail/skypeforlinux.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Warning: noroot option is not available
Parent pid 14585, child pid 14586
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 55.46 ms

Parent is shutting down, bye...
[realgecko@archlinux ~]$ uname -a
Linux archlinux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
[realgecko@archlinux ~]$
```
At the first login attempt skype fails to login, after second it simply closes by itself.

**Comment by Real-Gecko** [comment] 2018-01-22 08:32
And also:
```
noblacklist /var/run/systemd
read-only /var/run/systemd
```
did not help too.

**Comment by smitsohu** [comment] 2018-01-24 21:22
@Real-Gecko Can you try with `firejail --ignore=private-dev skypeforlinux`?

**Comment by Real-Gecko** [comment] 2018-01-25 05:28
This helped, I was able to login. So, what does it mean?

**Comment by smitsohu** [comment] 2018-01-25 12:38
@Real-Gecko It is a bug in firejail that will be fixed in the upcoming release (there are some more details in #1740).

For the meantime go to /etc/firejail/skypeforlinux.profile and comment private-dev (add a # in front of it), that will get it running.

**Comment by Real-Gecko** [comment] 2018-01-26 04:27
OK, thanks for your help, and for your app :)

**Comment by akontsevich** [comment] 2018-02-28 15:10
Guys, how to run `skypeforlinux` with firejail correctly so it won't see home dir? I tried like mentioned in #1740:

`firejail --profile=~/.config/firejail/skypeforlinux.profile skypeforlinux`

got:
```> skypeforlinux 
/usr/bin/skypeforlinux: line 3: /usr/bin/readlink: Permission denied
dirname: missing operand
Try 'dirname --help' for more information.
/usr/bin/skypeforlinux: line 4: /usr/bin/readlink: Permission denied
/usr/bin/skypeforlinux: line 9: /usr/bin/mkdir: Permission denied```

**Comment by chiraag-nataraj** [comment] 2019-05-29 20:41
@badpenguin never responded to the request for more information. @Real-Gecko, seems like your issue was resolved. @akontsevich, I will be closing this issue due to inactivity, but please feel free to re-open if this is still not working for you.

**Closed by chiraag-nataraj** 2019-05-29 20:41 UTC
Labels: information

**Comment by Real-Gecko** [comment] 2019-05-30 04:28
Yeah, I can confirm it works with 0.9.58.2. Thanks!
