### ISSUE TITLE
Disable creation of wrapper for single binary

### ISSUE THREAD

**Issue by WhyNotHugo** [netblue30/firejail#5241] opened 2022-07-07 07:39 UTC
### Is your feature request related to a problem? Please describe.

I have a system hook that runs `firecfg` each time a file is installed into `/usr/bin`.

However, this re-creates some link in `/usr/local/bin` that I don't want because sandboxing those applications is problematic.

I do want the links for _most_ binaries, but I want a few exceptions.

### Describe the solution you'd like

Some form of configuration file where I can specify names to skip when running `firecfg`.

### Describe alternatives you've considered

Deleting the profiles should be possible, but since those are provided by `firejail`, they'll get reinstalled on update. I'm not a fan of altering / deleting package-provided files anyway.

It should be possible to instruct the package manager to ignore installing unwanted profiles, but that's not very portable and sounds like a big hack.

### Additional context

I mostly want to disable to link in `/usr/local/bin/` for some programs where the sandbox does not work well for me or still needs to be refined more.

**Comment by reinerh** [comment] 2022-07-07 17:16
firecfg is only creating symlinks for programs/profiles that are mentioned in `/etc/firejail/firecfg.config`. Does this solve your problem?

**Comment by rusty-snake** [comment] 2022-07-07 18:19
Duplicate of #2097

**Closed by rusty-snake** 2022-07-07 18:19 UTC
Labels: duplicate, firecfg
