### ISSUE TITLE
Firejail sould be released as AppImage

### ISSUE THREAD

**Issue by karam72** [netblue30/firejail#5039] opened 2022-03-13 08:09 UTC
Hi,

It would be great if Firejail itself could be run as AppImage. Example:

> firejail.appImage --net=none vlc

It would great especially for user who don't have password of root (example on my company they don't give us the root password. So I can not use Firefail. But if Firejail was appImage, I would able to use it).

Thank you

**Comment by rusty-snake** [comment] 2022-03-13 08:11
Duplicate of #2849

**Closed by rusty-snake** 2022-03-13 08:11 UTC
