### ISSUE TITLE
Fedora silverblue flatpak of firejail

### ISSUE THREAD

**Issue by monterrr** [netblue30/firejail#3025] opened 2019-11-04 17:58 UTC
Fedora silverblue is an immutable OS, apps are supposed to be installed using flatpaks so how would one run firejail in this case that layering rpms is discouraged?

Is it possible to install and use firejail from a flatpak considering it will be running in a sandbox - a tool that is supposed to provide sandbox itself?

**Comment by rusty-snake** [comment] 2019-11-04 18:31
> Is it possible to install and use firejail from a flatpak

No, because of the sandbox. Also flatpak is used in silverblue for Grafical-Apps only IIRC.

firejail + Fedora silverblue doesn't work (see #2798), and I think it will never work.

(closing this as duplicate of #2798).

**Closed by rusty-snake** 2019-11-04 18:31 UTC
