### ISSUE TITLE
Opera not starting after updating profiles

### ISSUE THREAD

**Issue by saddy001** [netblue30/firejail#4929] opened 2022-02-11 09:35 UTC
This is Ubuntu 20.04, firejail 0.9.68. Updated the firejail profiles yesterday, now Opera won't start. Complaints:

```
Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 3643, child pid 3644
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Child process initialized in 134.37 ms
[9:9:0211/072306.550509:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[1:1:0211/072306.551127:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[6:27:0211/072306.680970:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:27:0211/072306.681046:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:27:0211/072306.681115:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:27:0211/072306.681156:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:27:0211/072306.681194:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied

(opera:6): GLib-GIO-ERROR **: 07:23:06.794: No GSettings schemas are installed on the system
[63:63:0211/072306.892153:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[1:1:0211/072306.897547:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[49:81:0211/072306.975671:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[49:81:0211/072306.975794:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[49:81:0211/072306.975899:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[49:81:0211/072306.975972:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[49:81:0211/072306.976025:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied

(opera:49): GLib-GIO-ERROR **: 07:23:07.035: No GSettings schemas are installed on the system
[1:1:0211/072307.114491:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[111:111:0211/072307.131171:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[104:135:0211/072307.191340:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[104:135:0211/072307.191418:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[104:135:0211/072307.191512:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[104:135:0211/072307.191570:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[104:135:0211/072307.191628:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied

(opera:104): GLib-GIO-ERROR **: 07:23:07.244: No GSettings schemas are installed on the system
[165:165:0211/072307.353688:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[1:1:0211/072307.355208:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[158:188:0211/072307.468109:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[158:188:0211/072307.468275:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[158:188:0211/072307.468348:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[158:188:0211/072307.468393:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[158:188:0211/072307.468461:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied

(opera:158): GLib-GIO-ERROR **: 07:23:07.512: No GSettings schemas are installed on the system

Parent is shutting down, bye...
```
I fixed the GSettings problem by adding --whitelist=/usr/share/glib-2.0/schemas. Opera starts, but it cannot fetch stored passwords. I have KeePassXC running. Think it's related to the dbus errors above? Maybe https://github.com/netblue30/firejail/issues/4917 also related.

**Comment by saddy001** [comment] 2022-02-11 09:39
Tried

https://github.com/netblue30/firejail/issues/4917#issuecomment-1033595197
> Ok, then add them back and try to remove
> 
> https://github.com/netblue30/firejail/blob/d18aec71012de00b06c822e99dd7fb3248f4ba1b/etc/profile-a-l/iridium.profile#L8-L11
> 
> You maybe need to add something like `whitelist /usr/share/iridium` if it exists.

But password store retrieval still not working.

**Comment by saddy001** [comment] 2022-02-11 09:41
For sake of completeness, here's the log after GSettings fix (successful start):

```
Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 15176, child pid 15177
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: not remounting /run/user/1000/gvfs
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Child process initialized in 115.79 ms
[9:9:0211/092157.143702:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[1:1:0211/092157.150991:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: failed to map segment from shared object)
[6:25:0211/092157.270096:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:25:0211/092157.270153:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:25:0211/092157.270207:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:25:0211/092157.270242:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:25:0211/092157.270276:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Permission denied
[6:6:0211/092157.435879:ERROR:url_pattern_set.cc(291)] Invalid url pattern: chrome://startpage/
[6:6:0211/092157.436008:ERROR:url_pattern_set.cc(291)] Invalid url pattern: chrome://startpage/
[6:6:0211/092157.436049:ERROR:url_pattern_set.cc(291)] Invalid url pattern: chrome://startpage/
[6:16:0211/092157.872806:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
[6:6:0211/092158.052114:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source: chrome://startpage/ (0)
[34:38:0211/092159.756471:ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -100
```

**Comment by rusty-snake** [comment] 2022-02-11 09:49
```
$ git grep "ignore whitelist /usr/share/chromium"
etc/profile-a-l/bnox.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/dnox.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/enox.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/flashpeak-slimjet.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/google-chrome-beta.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/google-chrome-unstable.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/google-chrome.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/inox.profile:ignore whitelist /usr/share/chromium
etc/profile-a-l/iridium.profile:ignore whitelist /usr/share/chromium
etc/profile-m-z/opera-beta.profile:ignore whitelist /usr/share/chromium
etc/profile-m-z/opera.profile:ignore whitelist /usr/share/chromium
etc/profile-m-z/snox.profile:ignore whitelist /usr/share/chromium
etc/profile-m-z/yandex-browser.profile:ignore whitelist /usr/share/chromium
```

We will need to add 
```
whitelist /usr/share/mozilla/extensions
whitelist /usr/share/webext
```
to all of them.

**Comment by saddy001** [comment] 2022-02-11 11:23
Thanks. Are there command line switches for these two parameters above? I'd like to avoid a custom profile as long as I can. 
Could take a while until the patches will reach the Ubuntu repos.

**Comment by rusty-snake** [comment] 2022-02-11 11:34
1. Just add them to your opera.local
2. Since they will be included in the next release, you could just edit opera.profile
3. > `--ignore=command`

**Comment by saddy001** [comment] 2022-02-11 11:40
I decided for option 2. but still no autofill. I added these lines in between in in /etc/firejail/opera.profile:

```
...
# Disable for now, see https://www.tutorialspoint.com/difference-between-void-main-and-int-main-in-c-cplusplus
 ignore whitelist /usr/share/chromium
 ignore include whitelist-runuser-common.inc
 ignore include whitelist-usr-share-common.inc

ignore whitelist /usr/share/mozilla/extensions
ignore whitelist /usr/share/webext

noblacklist ${HOME}/.cache/opera
noblacklist ${HOME}/.config/opera
noblacklist ${HOME}/.opera
...
```
Is something wrong with that?

**Comment by saddy001** [comment] 2022-02-17 08:19
I found out it's a bit different. Autofill seemed not to work because there were no entries anymore since the profiles update. However, I can store new entries and they are accessable after that. The question is, what happened to the old entries? Maybe they are stored in a different location now?
Since autofill works and I have backups of the old entries it's no issue for me now. Ticket can be closed.

**Comment by saddy001** [comment] 2022-02-17 09:13
I take it back. Password entries are not accessible again after restarting Opera.

**Comment by smitsohu** [comment] 2022-03-05 17:56
Does it work if you start opera this way: `firejail --ignore=whitelist opera` ?

If yes please try the following: Head to /etc/firejail/firejail.config and (only for debugging) append a line 
`seccomp-filter-add !chroot`

Then run `firejail --build opera`, try to get your passwords, and exit. At this point you should see many recommendations for `whitelist` directives, which may give a hint to what's missing here.

**Comment by saddy001** [comment] 2022-03-06 11:15
It's hard to say since I have stored my passwords again in the meantime. However, they are accessible and the gsettings workaround seems not necessary anymore. Since I have backed up my passwords before, I skipped your steps 2 and 3.

```
$ firejail --blacklist=/media --ignore=whitelist opera
Reading profile /etc/firejail/opera.profile
Reading profile /etc/firejail/chromium-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-run-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Warning: networking feature is disabled in Firejail configuration file
Parent pid 13060, child pid 13061
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: not remounting /run/user/1000/gvfs
Warning: NVIDIA card detected, nogroups command ignored
Warning: cleaning all supplementary groups
Child process initialized in 116.99 ms
[5:5:0306/121053.613770:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: Fehler beim Mappen des Shared Objects)
[1:1:0306/121053.615563:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: Fehler beim Mappen des Shared Objects)
[2:22:0306/121053.692348:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Keine Berechtigung
[2:22:0306/121053.692471:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Keine Berechtigung
[2:22:0306/121053.692537:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Keine Berechtigung
[2:22:0306/121053.692598:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Keine Berechtigung
[2:22:0306/121053.692642:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/firejail/mnt/dbus/system: Keine Berechtigung
[2:2:0306/121053.860370:ERROR:url_pattern_set.cc(259)] Invalid url pattern: chrome://startpage/
[2:2:0306/121053.860507:ERROR:url_pattern_set.cc(259)] Invalid url pattern: chrome://startpage/
[2:2:0306/121053.860546:ERROR:url_pattern_set.cc(259)] Invalid url pattern: chrome://startpage/
[2:25:0306/121054.392787:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
[2:2:0306/121057.024150:ERROR:named_platform_channel_posix.cc(146)] connect /home/user/.config/opera/oauc_pipe_r: Verbindungsaufbau abgelehnt (111)
[41:4:0306/121104.914944:ERROR:node_controller.cc(585)] Trying to re-add dropped peer D659092A2EDD2075.F5804434CB64E7E0
[41:4:0306/121104.922207:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 95BC8E75D9AC09F0.7410BA8570A58CA7
```

**Comment by glitsj16** [comment] 2022-03-07 00:42
> [5:5:0306/121053.613770:ERROR:content_main_runner_impl.cc(434)] Unable to load CDM /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so (error: /home/user/.config/opera/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: Fehler beim Mappen des Shared Objects)

Those Widevine errors relate to `include disable-exec.inc` and the conditional `'?BROWSER_ALLOW_DRM: ignore noexec ${HOME}` from `chromium-common.profile`. If you haven't changed any defaults in /etc/firejail/firejail.config this particular conditional returns 'false', the noexec is never ignored and Opera complains about it.

```console
$ grep -i drm /etc/firejail/firejail.config
# Allow (DRM) execution in browsers, default disabled.
# browser-allow-drm no

```

Most of the other errors I see here to, but they don't seem to break any functionality. Like the bus.cc lines, to be expected due to 'dbus-system none'. Some also show up when running non-girejailed (Invalid url pattern for example). That leaves the NSS one, which doesn't show for me. In fact, I can't reproduce any of this on Arch Linux with Firejail built from git and opera 84.0.4316.31. Passwords are accessible, show up in Opera's settings, can be exported and autofill functions properly. Only thing changed from defaults is I `include chromium-common-hardened.inc.profile` in a chromium-common.local for extra hardening. We haven't much to go on yet to really help, which leads to more questions...

Do you use the deb.opera.com repository on your Ubuntu? Is the Opera's internal sandbox SUID on your installation? Check these specifics please and report back.

```
$ grep -i drm /etc/firejail/firejail.config
$ stat -c %a /usr/lib/x86_64-linux-gnu/opera/opera_sandbox
$ firejail --blacklist=/media --ignore=noexec /usr/bin/opera
```

**Comment by saddy001** [comment] 2022-03-07 07:23
I assume the password problem is (or was) related to my use of KeePassXC as mentioned in an earlier post. To my knowledge it intercepts the browser's password accesses but I don't know the technical details. 

At the moment, I'm able to start opera again and access my passwords so we can close this ticket?

```
$ grep -i drm /etc/firejail/firejail.config
# Allow (DRM) execution in browsers, default disabled.
# browser-allow-drm no
$ stat -c %a /usr/lib/x86_64-linux-gnu/opera/opera_sandbox
4755
```

**Comment by glitsj16** [comment] 2022-03-07 10:14
Thanks for posting the outputs, they're fine. Just remember to add `ignore noexec ${HOME}` in opera.local if you want to play DRM protected content.

> At the moment, I'm able to start opera again and access my passwords so we can close this ticket?

I don't have anything else so personally I'm fine with closing here. @netblue30 marked this as a bug so I'll leave it up to him. There might be something he wants to look at.

**Comment by netblue30** [comment] 2022-03-11 14:44
Let's close it, not a bug on our side. Thanks!

**Closed by netblue30** 2022-03-11 14:44 UTC
