### ISSUE TITLE
audacity: error while loading shared libraries: lib-project-rate.so

### ISSUE THREAD

**Issue by a51kot** [netblue30/firejail#5466] opened 2022-11-10 19:22 UTC
Audacity its crashing!

```
firejail audacity
Reading profile /etc/firejail/audacity.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/disable-shell.inc
Reading profile /etc/firejail/disable-xdg.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Parent pid 48583, child pid 48584
1 program installed in 191.92 ms
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: not remounting /run/user/1000/doc
Warning: not remounting /run/user/1000/gvfs
Blacklist violations are logged to syslog
Warning: Cannot confine the application using AppArmor.
Maybe firejail-default AppArmor profile is not loaded into the kernel.
As root, run "aa-enforce firejail-default" to load it.
Child process initialized in 593.80 ms
audacity: error while loading shared libraries: lib-project-rate.so: cannot open shared object file: No such file or directory

Parent is shutting down, bye...

```

Cinelerra-GG https://aur.archlinux.org/packages/cinelerra-gg

```
firejail cinelerra-gg
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 49332, child pid 49333
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Child process initialized in 222.70 ms
Cinelerra Infinity - built: Nov  4 2022 02:08:10
git://git.cinelerra-gg.org/goodguy/cinelerra.git
(c) 2006-2019 Heroine Virtual Ltd. by Adam Williams
2007-2020 mods for Cinelerra-GG by W.P.Morrow aka goodguy
Cinelerra is free software, covered by the GNU General Public License,
and you are welcome to change it and/or distribute copies of it under
certain conditions. There is absolutely no warranty for Cinelerra.

lang changed from '' to 'en_US'
MWindow::init_plugins: can't open plugin index: /home/senpai/.bcast5/Cinelerra_plugins
MWindow::init_ladspa_plugins: can't open ladspa plugin index: /home/senpai/.bcast5/ladspa_plugins._usr_lib_cinelerra-gg_ladspa
MWindow::init_theme: prefered theme Cakewalk not found.
MWindow::init_theme: theme_plugin not found.
unjoined tids / owner 1
  00007f6f3b7fe6c0 / 00007f6f541ef800 12BC_Clipboard

Parent is shutting down, bye...

```

Version 0.7.0  
Host Archlinux/Manjaro

---

EDIT by @rusty-snake: Fix code-block.

**Comment by rusty-snake** [comment] 2022-11-10 19:43
You have two issues, they should have two issues.

You said "stopped working", stopped working after what? And updated or out of nowhere?

As you can see cinelerra-gg does not have a profile, either request one in #1139 or write your own one.

For audacity we can help you much better if you provide necessary information. The easiest way to do so is to use our bug template.

**Comment by glitsj16** [comment] 2022-11-10 20:01
Regarding `audacity`, I just installed it on my arch linux box. The `private-bin audacity` is breaking it. Haven't found the time yet to dig into this deeper, but for now you can work around this by creating a `~/.config/firejail/audacity.local` with the below content:

```
ignore private-bin
```

Regarding `cinelerra-gg` from the AUR. It renames the executable to cinelerra-gg, which, as pointed out by @rusty-snake isn't supported by firejail (yet). All that's needed is another redirect profile and I'm willing to add that. Before I do so, can you add the below in `~/.config/firejail/cinelerra-gg.profile`, test it and report back:

```
# Firejail profile alias for cin
# This file is overwritten after every install/update
# Persistent local customizations
include cinelerra-gg.local
# Persistent global definitions
# added by included profile
#include globals.local

# Redirect
include cin.profile
```

**Comment by kmk3** [comment] 2024-08-23 16:38
Duplicate of #5532

**Closed by kmk3** 2024-08-23 16:38 UTC
Labels: duplicate
