### ISSUE TITLE
Firefox des not start anymore

### ISSUE THREAD

**Issue by MrFrank17** [netblue30/firejail#4224] opened 2021-04-29 20:31 UTC
Hi,

lately on my Kubuntu 20.10 machine (not updated to  21.04 yet) firefox and firejail do not play nice anymore: FF does not start at all (using FF 88.0).
Interestingly `firejail --noprofile firefox` and also `firejail firefox --safe-mode` both work. Because of the working safemode I thought that maybe an add-on causes problems and deactivated all of them - but without success.

Now I am stuck - any ideas?

When starting FF in the console I got as output:

`Warning: networking feature is disabled in Firejail configuration file
Parent pid 238360, child pid 238361
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Warning: cleaning all supplementary groups
Post-exec seccomp protector enabled
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 111.98 ms`

With journalctl:
`SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=firejail-default pid=238370 comm="GLXVsyncThread" exe="/usr/lib/firefox/firefox" sig=31 arch=c000003e syscall=312 compat=0 ip=0x7fd52482467d code=0x0`

Thanks
Frank

**Comment by glitsj16** [comment] 2021-04-30 01:16
Sounds like https://github.com/netblue30/firejail/issues/3420.

**Comment by rusty-snake** [comment] 2021-04-30 05:56
Duplicate of #3219

**Comment by rusty-snake** [comment] 2021-04-30 05:56
Duplicate of #3420

**Comment by rusty-snake** [comment] 2021-04-30 05:59
`mkdir -p ~/.config/firejail && echo -e 'seccomp !chroot,!kcmp\nignore seccomp' >> ~/.config/firejail/firefox.local

**Closed** 2021-04-30 06:00 UTC
Labels: duplicate
